transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/xbip_utils_v3_0_11
vlib riviera/axi_utils_v2_0_7
vlib riviera/xbip_pipe_v3_0_7
vlib riviera/xbip_dsp48_wrapper_v3_0_5
vlib riviera/xbip_dsp48_addsub_v3_0_7
vlib riviera/xbip_dsp48_multadd_v3_0_7
vlib riviera/xbip_bram18k_v3_0_7
vlib riviera/mult_gen_v12_0_19
vlib riviera/floating_point_v7_1_16
vlib riviera/xil_defaultlib
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_15
vlib riviera/zynq_ultra_ps_e_vip_v1_0_15
vlib riviera/generic_baseblocks_v2_1_1
vlib riviera/axi_register_slice_v2_1_29
vlib riviera/fifo_generator_v13_2_9
vlib riviera/axi_data_fifo_v2_1_28
vlib riviera/axi_crossbar_v2_1_30
vlib riviera/axi_protocol_converter_v2_1_29
vlib riviera/axi_clock_converter_v2_1_28
vlib riviera/blk_mem_gen_v8_4_7
vlib riviera/axi_dwidth_converter_v2_1_29
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_14
vlib riviera/xlconstant_v1_1_8
vlib riviera/smartconnect_v1_0

vmap xilinx_vip riviera/xilinx_vip
vmap xpm riviera/xpm
vmap xbip_utils_v3_0_11 riviera/xbip_utils_v3_0_11
vmap axi_utils_v2_0_7 riviera/axi_utils_v2_0_7
vmap xbip_pipe_v3_0_7 riviera/xbip_pipe_v3_0_7
vmap xbip_dsp48_wrapper_v3_0_5 riviera/xbip_dsp48_wrapper_v3_0_5
vmap xbip_dsp48_addsub_v3_0_7 riviera/xbip_dsp48_addsub_v3_0_7
vmap xbip_dsp48_multadd_v3_0_7 riviera/xbip_dsp48_multadd_v3_0_7
vmap xbip_bram18k_v3_0_7 riviera/xbip_bram18k_v3_0_7
vmap mult_gen_v12_0_19 riviera/mult_gen_v12_0_19
vmap floating_point_v7_1_16 riviera/floating_point_v7_1_16
vmap xil_defaultlib riviera/xil_defaultlib
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_15 riviera/axi_vip_v1_1_15
vmap zynq_ultra_ps_e_vip_v1_0_15 riviera/zynq_ultra_ps_e_vip_v1_0_15
vmap generic_baseblocks_v2_1_1 riviera/generic_baseblocks_v2_1_1
vmap axi_register_slice_v2_1_29 riviera/axi_register_slice_v2_1_29
vmap fifo_generator_v13_2_9 riviera/fifo_generator_v13_2_9
vmap axi_data_fifo_v2_1_28 riviera/axi_data_fifo_v2_1_28
vmap axi_crossbar_v2_1_30 riviera/axi_crossbar_v2_1_30
vmap axi_protocol_converter_v2_1_29 riviera/axi_protocol_converter_v2_1_29
vmap axi_clock_converter_v2_1_28 riviera/axi_clock_converter_v2_1_28
vmap blk_mem_gen_v8_4_7 riviera/blk_mem_gen_v8_4_7
vmap axi_dwidth_converter_v2_1_29 riviera/axi_dwidth_converter_v2_1_29
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_14 riviera/proc_sys_reset_v5_0_14
vmap xlconstant_v1_1_8 riviera/xlconstant_v1_1_8
vmap smartconnect_v1_0 riviera/smartconnect_v1_0

vlog -work xilinx_vip  -incr "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"E:/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xbip_utils_v3_0_11 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/9836/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -work axi_utils_v2_0_7 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/e392/hdl/axi_utils_v2_0_vh_rfs.vhd" \

vcom -work xbip_pipe_v3_0_7 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c4f2/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -work xbip_dsp48_wrapper_v3_0_5 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/e5f6/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

vcom -work xbip_dsp48_addsub_v3_0_7 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/9cc0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

vcom -work xbip_dsp48_multadd_v3_0_7 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/0fb3/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \

vcom -work xbip_bram18k_v3_0_7 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/7a2e/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

vcom -work mult_gen_v12_0_19 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/e1b5/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -work floating_point_v7_1_16 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/0994/hdl/floating_point_v7_1_rfs.vhd" \

vlog -work floating_point_v7_1_16  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/0994/hdl/floating_point_v7_1_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain_ctrl_s_axi.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain_data0_m_axi.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain_data1_m_axi.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain_data2_m_axi.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain_fadd_32ns_32ns_32_4_full_dsp_1.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain_fmul_32ns_32ns_32_3_max_dsp_1.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/verilog/matmul_plain.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/ip/matmul_plain_fadd_32ns_32ns_32_4_full_dsp_1_ip.v" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c940/hdl/ip/matmul_plain_fmul_32ns_32ns_32_3_max_dsp_1_ip.v" \
"../../../bd/design_1/ip/design_1_matmul_plain_0_1/sim/design_1_matmul_plain_0_1.v" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_15  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work zynq_ultra_ps_e_vip_v1_0_15  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/sim/design_1_zynq_ultra_ps_e_0_1_vip_wrapper.v" \

vlog -work generic_baseblocks_v2_1_1  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/10ab/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_29  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_9  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ac72/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_9 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_9  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ac72/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_28  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/279e/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_30  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/fb47/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \

vlog -work axi_protocol_converter_v2_1_29  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/a63f/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work axi_clock_converter_v2_1_28  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/769c/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work blk_mem_gen_v8_4_7  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/3c0c/simulation/blk_mem_gen_v8_4.v" \

vlog -work axi_dwidth_converter_v2_1_29  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/670d/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
"../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
"../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
"../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \

vcom -work lib_cdc_v1_0_2 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_14 -93  -incr \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_rst_ps8_0_99M_1/sim/design_1_rst_ps8_0_99M_1.vhd" \

vlog -work xlconstant_v1_1_8  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_0/sim/bd_6f02_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_1/sim/bd_6f02_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_2/sim/bd_6f02_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_3/sim/bd_6f02_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_4/sim/bd_6f02_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_5/sim/bd_6f02_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_6/sim/bd_6f02_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_7/sim/bd_6f02_srn_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_8/sim/bd_6f02_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/ip/ip_9/sim/bd_6f02_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/bd_0/sim/bd_6f02.v" \

vlog -work smartconnect_v1_0  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1/sim/design_1_axi_smc_1.v" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_0/sim/bd_a878_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_1/sim/bd_a878_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_2/sim/bd_a878_s00mmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_3/sim/bd_a878_s00tr_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_4/sim/bd_a878_s00sic_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_5/sim/bd_a878_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_6/sim/bd_a878_sarn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_7/sim/bd_a878_srn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_8/sim/bd_a878_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/ip/ip_9/sim/bd_a878_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/bd_0/sim/bd_a878.v" \
"../../../bd/design_1/ip/design_1_axi_smc_1_0/sim/design_1_axi_smc_1_0.v" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_0/sim/bd_a888_one_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_1/sim/bd_a888_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -incr "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_2/sim/bd_a888_s00mmu_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_3/sim/bd_a888_s00tr_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_4/sim/bd_a888_s00sic_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_5/sim/bd_a888_s00a2s_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_6/sim/bd_a888_sawn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_7/sim/bd_a888_swn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_8/sim/bd_a888_sbn_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_9/sim/bd_a888_m00s2a_0.sv" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/ip/ip_10/sim/bd_a888_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/ec67/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/2fcd/hdl" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/f0b6/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ipshared/35de/hdl/verilog" "+incdir+../../../../matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_matmul_plain_0_1/drivers/matmul_plain_v1_0/src" "+incdir+E:/Xilinx/Vivado/2023.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_11 -l axi_utils_v2_0_7 -l xbip_pipe_v3_0_7 -l xbip_dsp48_wrapper_v3_0_5 -l xbip_dsp48_addsub_v3_0_7 -l xbip_dsp48_multadd_v3_0_7 -l xbip_bram18k_v3_0_7 -l mult_gen_v12_0_19 -l floating_point_v7_1_16 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_15 -l zynq_ultra_ps_e_vip_v1_0_15 -l generic_baseblocks_v2_1_1 -l axi_register_slice_v2_1_29 -l fifo_generator_v13_2_9 -l axi_data_fifo_v2_1_28 -l axi_crossbar_v2_1_30 -l axi_protocol_converter_v2_1_29 -l axi_clock_converter_v2_1_28 -l blk_mem_gen_v8_4_7 -l axi_dwidth_converter_v2_1_29 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_14 -l xlconstant_v1_1_8 -l smartconnect_v1_0 \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/bd_0/sim/bd_a888.v" \
"../../../bd/design_1/ip/design_1_axi_smc_2_0/sim/design_1_axi_smc_2_0.v" \
"../../../bd/design_1/sim/design_1.v" \

vlog -work xil_defaultlib \
"glbl.v"

