// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fc6_hls_fc6_hls,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=3826,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=5143,HLS_SYN_LUT=5025,HLS_VERSION=2023_2}" *)

module fc6_hls (
        ap_clk,
        ap_rst_n,
        m_axi_INPUT_r_AWVALID,
        m_axi_INPUT_r_AWREADY,
        m_axi_INPUT_r_AWADDR,
        m_axi_INPUT_r_AWID,
        m_axi_INPUT_r_AWLEN,
        m_axi_INPUT_r_AWSIZE,
        m_axi_INPUT_r_AWBURST,
        m_axi_INPUT_r_AWLOCK,
        m_axi_INPUT_r_AWCACHE,
        m_axi_INPUT_r_AWPROT,
        m_axi_INPUT_r_AWQOS,
        m_axi_INPUT_r_AWREGION,
        m_axi_INPUT_r_AWUSER,
        m_axi_INPUT_r_WVALID,
        m_axi_INPUT_r_WREADY,
        m_axi_INPUT_r_WDATA,
        m_axi_INPUT_r_WSTRB,
        m_axi_INPUT_r_WLAST,
        m_axi_INPUT_r_WID,
        m_axi_INPUT_r_WUSER,
        m_axi_INPUT_r_ARVALID,
        m_axi_INPUT_r_ARREADY,
        m_axi_INPUT_r_ARADDR,
        m_axi_INPUT_r_ARID,
        m_axi_INPUT_r_ARLEN,
        m_axi_INPUT_r_ARSIZE,
        m_axi_INPUT_r_ARBURST,
        m_axi_INPUT_r_ARLOCK,
        m_axi_INPUT_r_ARCACHE,
        m_axi_INPUT_r_ARPROT,
        m_axi_INPUT_r_ARQOS,
        m_axi_INPUT_r_ARREGION,
        m_axi_INPUT_r_ARUSER,
        m_axi_INPUT_r_RVALID,
        m_axi_INPUT_r_RREADY,
        m_axi_INPUT_r_RDATA,
        m_axi_INPUT_r_RLAST,
        m_axi_INPUT_r_RID,
        m_axi_INPUT_r_RUSER,
        m_axi_INPUT_r_RRESP,
        m_axi_INPUT_r_BVALID,
        m_axi_INPUT_r_BREADY,
        m_axi_INPUT_r_BRESP,
        m_axi_INPUT_r_BID,
        m_axi_INPUT_r_BUSER,
        m_axi_WEIGHTS_AWVALID,
        m_axi_WEIGHTS_AWREADY,
        m_axi_WEIGHTS_AWADDR,
        m_axi_WEIGHTS_AWID,
        m_axi_WEIGHTS_AWLEN,
        m_axi_WEIGHTS_AWSIZE,
        m_axi_WEIGHTS_AWBURST,
        m_axi_WEIGHTS_AWLOCK,
        m_axi_WEIGHTS_AWCACHE,
        m_axi_WEIGHTS_AWPROT,
        m_axi_WEIGHTS_AWQOS,
        m_axi_WEIGHTS_AWREGION,
        m_axi_WEIGHTS_AWUSER,
        m_axi_WEIGHTS_WVALID,
        m_axi_WEIGHTS_WREADY,
        m_axi_WEIGHTS_WDATA,
        m_axi_WEIGHTS_WSTRB,
        m_axi_WEIGHTS_WLAST,
        m_axi_WEIGHTS_WID,
        m_axi_WEIGHTS_WUSER,
        m_axi_WEIGHTS_ARVALID,
        m_axi_WEIGHTS_ARREADY,
        m_axi_WEIGHTS_ARADDR,
        m_axi_WEIGHTS_ARID,
        m_axi_WEIGHTS_ARLEN,
        m_axi_WEIGHTS_ARSIZE,
        m_axi_WEIGHTS_ARBURST,
        m_axi_WEIGHTS_ARLOCK,
        m_axi_WEIGHTS_ARCACHE,
        m_axi_WEIGHTS_ARPROT,
        m_axi_WEIGHTS_ARQOS,
        m_axi_WEIGHTS_ARREGION,
        m_axi_WEIGHTS_ARUSER,
        m_axi_WEIGHTS_RVALID,
        m_axi_WEIGHTS_RREADY,
        m_axi_WEIGHTS_RDATA,
        m_axi_WEIGHTS_RLAST,
        m_axi_WEIGHTS_RID,
        m_axi_WEIGHTS_RUSER,
        m_axi_WEIGHTS_RRESP,
        m_axi_WEIGHTS_BVALID,
        m_axi_WEIGHTS_BREADY,
        m_axi_WEIGHTS_BRESP,
        m_axi_WEIGHTS_BID,
        m_axi_WEIGHTS_BUSER,
        m_axi_BIAS_AWVALID,
        m_axi_BIAS_AWREADY,
        m_axi_BIAS_AWADDR,
        m_axi_BIAS_AWID,
        m_axi_BIAS_AWLEN,
        m_axi_BIAS_AWSIZE,
        m_axi_BIAS_AWBURST,
        m_axi_BIAS_AWLOCK,
        m_axi_BIAS_AWCACHE,
        m_axi_BIAS_AWPROT,
        m_axi_BIAS_AWQOS,
        m_axi_BIAS_AWREGION,
        m_axi_BIAS_AWUSER,
        m_axi_BIAS_WVALID,
        m_axi_BIAS_WREADY,
        m_axi_BIAS_WDATA,
        m_axi_BIAS_WSTRB,
        m_axi_BIAS_WLAST,
        m_axi_BIAS_WID,
        m_axi_BIAS_WUSER,
        m_axi_BIAS_ARVALID,
        m_axi_BIAS_ARREADY,
        m_axi_BIAS_ARADDR,
        m_axi_BIAS_ARID,
        m_axi_BIAS_ARLEN,
        m_axi_BIAS_ARSIZE,
        m_axi_BIAS_ARBURST,
        m_axi_BIAS_ARLOCK,
        m_axi_BIAS_ARCACHE,
        m_axi_BIAS_ARPROT,
        m_axi_BIAS_ARQOS,
        m_axi_BIAS_ARREGION,
        m_axi_BIAS_ARUSER,
        m_axi_BIAS_RVALID,
        m_axi_BIAS_RREADY,
        m_axi_BIAS_RDATA,
        m_axi_BIAS_RLAST,
        m_axi_BIAS_RID,
        m_axi_BIAS_RUSER,
        m_axi_BIAS_RRESP,
        m_axi_BIAS_BVALID,
        m_axi_BIAS_BREADY,
        m_axi_BIAS_BRESP,
        m_axi_BIAS_BID,
        m_axi_BIAS_BUSER,
        m_axi_OUTPUT_r_AWVALID,
        m_axi_OUTPUT_r_AWREADY,
        m_axi_OUTPUT_r_AWADDR,
        m_axi_OUTPUT_r_AWID,
        m_axi_OUTPUT_r_AWLEN,
        m_axi_OUTPUT_r_AWSIZE,
        m_axi_OUTPUT_r_AWBURST,
        m_axi_OUTPUT_r_AWLOCK,
        m_axi_OUTPUT_r_AWCACHE,
        m_axi_OUTPUT_r_AWPROT,
        m_axi_OUTPUT_r_AWQOS,
        m_axi_OUTPUT_r_AWREGION,
        m_axi_OUTPUT_r_AWUSER,
        m_axi_OUTPUT_r_WVALID,
        m_axi_OUTPUT_r_WREADY,
        m_axi_OUTPUT_r_WDATA,
        m_axi_OUTPUT_r_WSTRB,
        m_axi_OUTPUT_r_WLAST,
        m_axi_OUTPUT_r_WID,
        m_axi_OUTPUT_r_WUSER,
        m_axi_OUTPUT_r_ARVALID,
        m_axi_OUTPUT_r_ARREADY,
        m_axi_OUTPUT_r_ARADDR,
        m_axi_OUTPUT_r_ARID,
        m_axi_OUTPUT_r_ARLEN,
        m_axi_OUTPUT_r_ARSIZE,
        m_axi_OUTPUT_r_ARBURST,
        m_axi_OUTPUT_r_ARLOCK,
        m_axi_OUTPUT_r_ARCACHE,
        m_axi_OUTPUT_r_ARPROT,
        m_axi_OUTPUT_r_ARQOS,
        m_axi_OUTPUT_r_ARREGION,
        m_axi_OUTPUT_r_ARUSER,
        m_axi_OUTPUT_r_RVALID,
        m_axi_OUTPUT_r_RREADY,
        m_axi_OUTPUT_r_RDATA,
        m_axi_OUTPUT_r_RLAST,
        m_axi_OUTPUT_r_RID,
        m_axi_OUTPUT_r_RUSER,
        m_axi_OUTPUT_r_RRESP,
        m_axi_OUTPUT_r_BVALID,
        m_axi_OUTPUT_r_BREADY,
        m_axi_OUTPUT_r_BRESP,
        m_axi_OUTPUT_r_BID,
        m_axi_OUTPUT_r_BUSER,
        s_axi_CTRL_BUS_AWVALID,
        s_axi_CTRL_BUS_AWREADY,
        s_axi_CTRL_BUS_AWADDR,
        s_axi_CTRL_BUS_WVALID,
        s_axi_CTRL_BUS_WREADY,
        s_axi_CTRL_BUS_WDATA,
        s_axi_CTRL_BUS_WSTRB,
        s_axi_CTRL_BUS_ARVALID,
        s_axi_CTRL_BUS_ARREADY,
        s_axi_CTRL_BUS_ARADDR,
        s_axi_CTRL_BUS_RVALID,
        s_axi_CTRL_BUS_RREADY,
        s_axi_CTRL_BUS_RDATA,
        s_axi_CTRL_BUS_RRESP,
        s_axi_CTRL_BUS_BVALID,
        s_axi_CTRL_BUS_BREADY,
        s_axi_CTRL_BUS_BRESP,
        interrupt,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_state5 = 32'd16;
parameter    ap_ST_fsm_state6 = 32'd32;
parameter    ap_ST_fsm_state7 = 32'd64;
parameter    ap_ST_fsm_state8 = 32'd128;
parameter    ap_ST_fsm_state9 = 32'd256;
parameter    ap_ST_fsm_state10 = 32'd512;
parameter    ap_ST_fsm_state11 = 32'd1024;
parameter    ap_ST_fsm_state12 = 32'd2048;
parameter    ap_ST_fsm_state13 = 32'd4096;
parameter    ap_ST_fsm_state14 = 32'd8192;
parameter    ap_ST_fsm_state15 = 32'd16384;
parameter    ap_ST_fsm_state16 = 32'd32768;
parameter    ap_ST_fsm_state17 = 32'd65536;
parameter    ap_ST_fsm_state18 = 32'd131072;
parameter    ap_ST_fsm_state19 = 32'd262144;
parameter    ap_ST_fsm_state20 = 32'd524288;
parameter    ap_ST_fsm_state21 = 32'd1048576;
parameter    ap_ST_fsm_state22 = 32'd2097152;
parameter    ap_ST_fsm_state23 = 32'd4194304;
parameter    ap_ST_fsm_state24 = 32'd8388608;
parameter    ap_ST_fsm_state25 = 32'd16777216;
parameter    ap_ST_fsm_state26 = 32'd33554432;
parameter    ap_ST_fsm_state27 = 32'd67108864;
parameter    ap_ST_fsm_state28 = 32'd134217728;
parameter    ap_ST_fsm_state29 = 32'd268435456;
parameter    ap_ST_fsm_state30 = 32'd536870912;
parameter    ap_ST_fsm_state31 = 32'd1073741824;
parameter    ap_ST_fsm_state32 = 32'd2147483648;
parameter    C_S_AXI_CTRL_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_BUS_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_M_AXI_BIAS_ID_WIDTH = 1;
parameter    C_M_AXI_BIAS_ADDR_WIDTH = 64;
parameter    C_M_AXI_BIAS_DATA_WIDTH = 32;
parameter    C_M_AXI_BIAS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_BIAS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_BIAS_WUSER_WIDTH = 1;
parameter    C_M_AXI_BIAS_RUSER_WIDTH = 1;
parameter    C_M_AXI_BIAS_BUSER_WIDTH = 1;
parameter    C_M_AXI_BIAS_USER_VALUE = 0;
parameter    C_M_AXI_BIAS_PROT_VALUE = 0;
parameter    C_M_AXI_BIAS_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_INPUT_R_ID_WIDTH = 1;
parameter    C_M_AXI_INPUT_R_ADDR_WIDTH = 64;
parameter    C_M_AXI_INPUT_R_DATA_WIDTH = 32;
parameter    C_M_AXI_INPUT_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_R_USER_VALUE = 0;
parameter    C_M_AXI_INPUT_R_PROT_VALUE = 0;
parameter    C_M_AXI_INPUT_R_CACHE_VALUE = 3;
parameter    C_M_AXI_OUTPUT_R_ID_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_ADDR_WIDTH = 64;
parameter    C_M_AXI_OUTPUT_R_DATA_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_USER_VALUE = 0;
parameter    C_M_AXI_OUTPUT_R_PROT_VALUE = 0;
parameter    C_M_AXI_OUTPUT_R_CACHE_VALUE = 3;
parameter    C_M_AXI_WEIGHTS_ID_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_ADDR_WIDTH = 64;
parameter    C_M_AXI_WEIGHTS_DATA_WIDTH = 32;
parameter    C_M_AXI_WEIGHTS_AWUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_WUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_RUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_BUSER_WIDTH = 1;
parameter    C_M_AXI_WEIGHTS_USER_VALUE = 0;
parameter    C_M_AXI_WEIGHTS_PROT_VALUE = 0;
parameter    C_M_AXI_WEIGHTS_CACHE_VALUE = 3;

parameter C_S_AXI_CTRL_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_BIAS_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_INPUT_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUTPUT_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WEIGHTS_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_INPUT_r_AWVALID;
input   m_axi_INPUT_r_AWREADY;
output  [C_M_AXI_INPUT_R_ADDR_WIDTH - 1:0] m_axi_INPUT_r_AWADDR;
output  [C_M_AXI_INPUT_R_ID_WIDTH - 1:0] m_axi_INPUT_r_AWID;
output  [7:0] m_axi_INPUT_r_AWLEN;
output  [2:0] m_axi_INPUT_r_AWSIZE;
output  [1:0] m_axi_INPUT_r_AWBURST;
output  [1:0] m_axi_INPUT_r_AWLOCK;
output  [3:0] m_axi_INPUT_r_AWCACHE;
output  [2:0] m_axi_INPUT_r_AWPROT;
output  [3:0] m_axi_INPUT_r_AWQOS;
output  [3:0] m_axi_INPUT_r_AWREGION;
output  [C_M_AXI_INPUT_R_AWUSER_WIDTH - 1:0] m_axi_INPUT_r_AWUSER;
output   m_axi_INPUT_r_WVALID;
input   m_axi_INPUT_r_WREADY;
output  [C_M_AXI_INPUT_R_DATA_WIDTH - 1:0] m_axi_INPUT_r_WDATA;
output  [C_M_AXI_INPUT_R_WSTRB_WIDTH - 1:0] m_axi_INPUT_r_WSTRB;
output   m_axi_INPUT_r_WLAST;
output  [C_M_AXI_INPUT_R_ID_WIDTH - 1:0] m_axi_INPUT_r_WID;
output  [C_M_AXI_INPUT_R_WUSER_WIDTH - 1:0] m_axi_INPUT_r_WUSER;
output   m_axi_INPUT_r_ARVALID;
input   m_axi_INPUT_r_ARREADY;
output  [C_M_AXI_INPUT_R_ADDR_WIDTH - 1:0] m_axi_INPUT_r_ARADDR;
output  [C_M_AXI_INPUT_R_ID_WIDTH - 1:0] m_axi_INPUT_r_ARID;
output  [7:0] m_axi_INPUT_r_ARLEN;
output  [2:0] m_axi_INPUT_r_ARSIZE;
output  [1:0] m_axi_INPUT_r_ARBURST;
output  [1:0] m_axi_INPUT_r_ARLOCK;
output  [3:0] m_axi_INPUT_r_ARCACHE;
output  [2:0] m_axi_INPUT_r_ARPROT;
output  [3:0] m_axi_INPUT_r_ARQOS;
output  [3:0] m_axi_INPUT_r_ARREGION;
output  [C_M_AXI_INPUT_R_ARUSER_WIDTH - 1:0] m_axi_INPUT_r_ARUSER;
input   m_axi_INPUT_r_RVALID;
output   m_axi_INPUT_r_RREADY;
input  [C_M_AXI_INPUT_R_DATA_WIDTH - 1:0] m_axi_INPUT_r_RDATA;
input   m_axi_INPUT_r_RLAST;
input  [C_M_AXI_INPUT_R_ID_WIDTH - 1:0] m_axi_INPUT_r_RID;
input  [C_M_AXI_INPUT_R_RUSER_WIDTH - 1:0] m_axi_INPUT_r_RUSER;
input  [1:0] m_axi_INPUT_r_RRESP;
input   m_axi_INPUT_r_BVALID;
output   m_axi_INPUT_r_BREADY;
input  [1:0] m_axi_INPUT_r_BRESP;
input  [C_M_AXI_INPUT_R_ID_WIDTH - 1:0] m_axi_INPUT_r_BID;
input  [C_M_AXI_INPUT_R_BUSER_WIDTH - 1:0] m_axi_INPUT_r_BUSER;
output   m_axi_WEIGHTS_AWVALID;
input   m_axi_WEIGHTS_AWREADY;
output  [C_M_AXI_WEIGHTS_ADDR_WIDTH - 1:0] m_axi_WEIGHTS_AWADDR;
output  [C_M_AXI_WEIGHTS_ID_WIDTH - 1:0] m_axi_WEIGHTS_AWID;
output  [7:0] m_axi_WEIGHTS_AWLEN;
output  [2:0] m_axi_WEIGHTS_AWSIZE;
output  [1:0] m_axi_WEIGHTS_AWBURST;
output  [1:0] m_axi_WEIGHTS_AWLOCK;
output  [3:0] m_axi_WEIGHTS_AWCACHE;
output  [2:0] m_axi_WEIGHTS_AWPROT;
output  [3:0] m_axi_WEIGHTS_AWQOS;
output  [3:0] m_axi_WEIGHTS_AWREGION;
output  [C_M_AXI_WEIGHTS_AWUSER_WIDTH - 1:0] m_axi_WEIGHTS_AWUSER;
output   m_axi_WEIGHTS_WVALID;
input   m_axi_WEIGHTS_WREADY;
output  [C_M_AXI_WEIGHTS_DATA_WIDTH - 1:0] m_axi_WEIGHTS_WDATA;
output  [C_M_AXI_WEIGHTS_WSTRB_WIDTH - 1:0] m_axi_WEIGHTS_WSTRB;
output   m_axi_WEIGHTS_WLAST;
output  [C_M_AXI_WEIGHTS_ID_WIDTH - 1:0] m_axi_WEIGHTS_WID;
output  [C_M_AXI_WEIGHTS_WUSER_WIDTH - 1:0] m_axi_WEIGHTS_WUSER;
output   m_axi_WEIGHTS_ARVALID;
input   m_axi_WEIGHTS_ARREADY;
output  [C_M_AXI_WEIGHTS_ADDR_WIDTH - 1:0] m_axi_WEIGHTS_ARADDR;
output  [C_M_AXI_WEIGHTS_ID_WIDTH - 1:0] m_axi_WEIGHTS_ARID;
output  [7:0] m_axi_WEIGHTS_ARLEN;
output  [2:0] m_axi_WEIGHTS_ARSIZE;
output  [1:0] m_axi_WEIGHTS_ARBURST;
output  [1:0] m_axi_WEIGHTS_ARLOCK;
output  [3:0] m_axi_WEIGHTS_ARCACHE;
output  [2:0] m_axi_WEIGHTS_ARPROT;
output  [3:0] m_axi_WEIGHTS_ARQOS;
output  [3:0] m_axi_WEIGHTS_ARREGION;
output  [C_M_AXI_WEIGHTS_ARUSER_WIDTH - 1:0] m_axi_WEIGHTS_ARUSER;
input   m_axi_WEIGHTS_RVALID;
output   m_axi_WEIGHTS_RREADY;
input  [C_M_AXI_WEIGHTS_DATA_WIDTH - 1:0] m_axi_WEIGHTS_RDATA;
input   m_axi_WEIGHTS_RLAST;
input  [C_M_AXI_WEIGHTS_ID_WIDTH - 1:0] m_axi_WEIGHTS_RID;
input  [C_M_AXI_WEIGHTS_RUSER_WIDTH - 1:0] m_axi_WEIGHTS_RUSER;
input  [1:0] m_axi_WEIGHTS_RRESP;
input   m_axi_WEIGHTS_BVALID;
output   m_axi_WEIGHTS_BREADY;
input  [1:0] m_axi_WEIGHTS_BRESP;
input  [C_M_AXI_WEIGHTS_ID_WIDTH - 1:0] m_axi_WEIGHTS_BID;
input  [C_M_AXI_WEIGHTS_BUSER_WIDTH - 1:0] m_axi_WEIGHTS_BUSER;
output   m_axi_BIAS_AWVALID;
input   m_axi_BIAS_AWREADY;
output  [C_M_AXI_BIAS_ADDR_WIDTH - 1:0] m_axi_BIAS_AWADDR;
output  [C_M_AXI_BIAS_ID_WIDTH - 1:0] m_axi_BIAS_AWID;
output  [7:0] m_axi_BIAS_AWLEN;
output  [2:0] m_axi_BIAS_AWSIZE;
output  [1:0] m_axi_BIAS_AWBURST;
output  [1:0] m_axi_BIAS_AWLOCK;
output  [3:0] m_axi_BIAS_AWCACHE;
output  [2:0] m_axi_BIAS_AWPROT;
output  [3:0] m_axi_BIAS_AWQOS;
output  [3:0] m_axi_BIAS_AWREGION;
output  [C_M_AXI_BIAS_AWUSER_WIDTH - 1:0] m_axi_BIAS_AWUSER;
output   m_axi_BIAS_WVALID;
input   m_axi_BIAS_WREADY;
output  [C_M_AXI_BIAS_DATA_WIDTH - 1:0] m_axi_BIAS_WDATA;
output  [C_M_AXI_BIAS_WSTRB_WIDTH - 1:0] m_axi_BIAS_WSTRB;
output   m_axi_BIAS_WLAST;
output  [C_M_AXI_BIAS_ID_WIDTH - 1:0] m_axi_BIAS_WID;
output  [C_M_AXI_BIAS_WUSER_WIDTH - 1:0] m_axi_BIAS_WUSER;
output   m_axi_BIAS_ARVALID;
input   m_axi_BIAS_ARREADY;
output  [C_M_AXI_BIAS_ADDR_WIDTH - 1:0] m_axi_BIAS_ARADDR;
output  [C_M_AXI_BIAS_ID_WIDTH - 1:0] m_axi_BIAS_ARID;
output  [7:0] m_axi_BIAS_ARLEN;
output  [2:0] m_axi_BIAS_ARSIZE;
output  [1:0] m_axi_BIAS_ARBURST;
output  [1:0] m_axi_BIAS_ARLOCK;
output  [3:0] m_axi_BIAS_ARCACHE;
output  [2:0] m_axi_BIAS_ARPROT;
output  [3:0] m_axi_BIAS_ARQOS;
output  [3:0] m_axi_BIAS_ARREGION;
output  [C_M_AXI_BIAS_ARUSER_WIDTH - 1:0] m_axi_BIAS_ARUSER;
input   m_axi_BIAS_RVALID;
output   m_axi_BIAS_RREADY;
input  [C_M_AXI_BIAS_DATA_WIDTH - 1:0] m_axi_BIAS_RDATA;
input   m_axi_BIAS_RLAST;
input  [C_M_AXI_BIAS_ID_WIDTH - 1:0] m_axi_BIAS_RID;
input  [C_M_AXI_BIAS_RUSER_WIDTH - 1:0] m_axi_BIAS_RUSER;
input  [1:0] m_axi_BIAS_RRESP;
input   m_axi_BIAS_BVALID;
output   m_axi_BIAS_BREADY;
input  [1:0] m_axi_BIAS_BRESP;
input  [C_M_AXI_BIAS_ID_WIDTH - 1:0] m_axi_BIAS_BID;
input  [C_M_AXI_BIAS_BUSER_WIDTH - 1:0] m_axi_BIAS_BUSER;
output   m_axi_OUTPUT_r_AWVALID;
input   m_axi_OUTPUT_r_AWREADY;
output  [C_M_AXI_OUTPUT_R_ADDR_WIDTH - 1:0] m_axi_OUTPUT_r_AWADDR;
output  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_OUTPUT_r_AWID;
output  [7:0] m_axi_OUTPUT_r_AWLEN;
output  [2:0] m_axi_OUTPUT_r_AWSIZE;
output  [1:0] m_axi_OUTPUT_r_AWBURST;
output  [1:0] m_axi_OUTPUT_r_AWLOCK;
output  [3:0] m_axi_OUTPUT_r_AWCACHE;
output  [2:0] m_axi_OUTPUT_r_AWPROT;
output  [3:0] m_axi_OUTPUT_r_AWQOS;
output  [3:0] m_axi_OUTPUT_r_AWREGION;
output  [C_M_AXI_OUTPUT_R_AWUSER_WIDTH - 1:0] m_axi_OUTPUT_r_AWUSER;
output   m_axi_OUTPUT_r_WVALID;
input   m_axi_OUTPUT_r_WREADY;
output  [C_M_AXI_OUTPUT_R_DATA_WIDTH - 1:0] m_axi_OUTPUT_r_WDATA;
output  [C_M_AXI_OUTPUT_R_WSTRB_WIDTH - 1:0] m_axi_OUTPUT_r_WSTRB;
output   m_axi_OUTPUT_r_WLAST;
output  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_OUTPUT_r_WID;
output  [C_M_AXI_OUTPUT_R_WUSER_WIDTH - 1:0] m_axi_OUTPUT_r_WUSER;
output   m_axi_OUTPUT_r_ARVALID;
input   m_axi_OUTPUT_r_ARREADY;
output  [C_M_AXI_OUTPUT_R_ADDR_WIDTH - 1:0] m_axi_OUTPUT_r_ARADDR;
output  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_OUTPUT_r_ARID;
output  [7:0] m_axi_OUTPUT_r_ARLEN;
output  [2:0] m_axi_OUTPUT_r_ARSIZE;
output  [1:0] m_axi_OUTPUT_r_ARBURST;
output  [1:0] m_axi_OUTPUT_r_ARLOCK;
output  [3:0] m_axi_OUTPUT_r_ARCACHE;
output  [2:0] m_axi_OUTPUT_r_ARPROT;
output  [3:0] m_axi_OUTPUT_r_ARQOS;
output  [3:0] m_axi_OUTPUT_r_ARREGION;
output  [C_M_AXI_OUTPUT_R_ARUSER_WIDTH - 1:0] m_axi_OUTPUT_r_ARUSER;
input   m_axi_OUTPUT_r_RVALID;
output   m_axi_OUTPUT_r_RREADY;
input  [C_M_AXI_OUTPUT_R_DATA_WIDTH - 1:0] m_axi_OUTPUT_r_RDATA;
input   m_axi_OUTPUT_r_RLAST;
input  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_OUTPUT_r_RID;
input  [C_M_AXI_OUTPUT_R_RUSER_WIDTH - 1:0] m_axi_OUTPUT_r_RUSER;
input  [1:0] m_axi_OUTPUT_r_RRESP;
input   m_axi_OUTPUT_r_BVALID;
output   m_axi_OUTPUT_r_BREADY;
input  [1:0] m_axi_OUTPUT_r_BRESP;
input  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_OUTPUT_r_BID;
input  [C_M_AXI_OUTPUT_R_BUSER_WIDTH - 1:0] m_axi_OUTPUT_r_BUSER;
input   s_axi_CTRL_BUS_AWVALID;
output   s_axi_CTRL_BUS_AWREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_AWADDR;
input   s_axi_CTRL_BUS_WVALID;
output   s_axi_CTRL_BUS_WREADY;
input  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_WDATA;
input  [C_S_AXI_CTRL_BUS_WSTRB_WIDTH - 1:0] s_axi_CTRL_BUS_WSTRB;
input   s_axi_CTRL_BUS_ARVALID;
output   s_axi_CTRL_BUS_ARREADY;
input  [C_S_AXI_CTRL_BUS_ADDR_WIDTH - 1:0] s_axi_CTRL_BUS_ARADDR;
output   s_axi_CTRL_BUS_RVALID;
input   s_axi_CTRL_BUS_RREADY;
output  [C_S_AXI_CTRL_BUS_DATA_WIDTH - 1:0] s_axi_CTRL_BUS_RDATA;
output  [1:0] s_axi_CTRL_BUS_RRESP;
output   s_axi_CTRL_BUS_BVALID;
input   s_axi_CTRL_BUS_BREADY;
output  [1:0] s_axi_CTRL_BUS_BRESP;
output   interrupt;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r_r;
wire   [63:0] weights_r;
wire   [63:0] bias_r;
wire   [63:0] output_r_r;
reg    INPUT_r_blk_n_AR;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state13;
reg    WEIGHTS_blk_n_AR;
reg    BIAS_blk_n_AR;
reg    BIAS_blk_n_R;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state22;
reg    OUTPUT_r_blk_n_AW;
reg    OUTPUT_r_blk_n_W;
wire    ap_CS_fsm_state17;
reg    OUTPUT_r_blk_n_B;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state32;
wire   [31:0] grp_fu_263_p2;
reg   [31:0] reg_267;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state26;
reg   [63:0] output_r_read_reg_565;
reg   [63:0] bias_read_reg_571;
reg   [63:0] weights_read_reg_577;
wire  signed [61:0] trunc_ln_fu_271_p4;
reg   [61:0] trunc_ln_reg_595;
reg   [63:0] INPUT_r_addr_reg_601;
reg   [61:0] trunc_ln24_1_reg_609;
wire    ap_CS_fsm_state2;
reg   [63:0] BIAS_addr_reg_615;
reg   [63:0] OUTPUT_r_addr_reg_621;
reg   [61:0] trunc_ln24_2_reg_627;
reg   [63:0] BIAS_addr_1_reg_633;
reg   [63:0] OUTPUT_r_addr_1_reg_639;
reg   [31:0] BIAS_addr_read_reg_650;
wire   [31:0] bitcast_ln32_fu_526_p1;
reg   [31:0] BIAS_addr_1_read_reg_668;
wire   [31:0] bitcast_ln32_2_fu_549_p1;
wire    ap_CS_fsm_state23;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_done;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_idle;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_ready;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WVALID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WDATA;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WSTRB;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WLAST;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WID;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_RREADY;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_BREADY;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WVALID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WDATA;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WSTRB;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WLAST;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WID;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_RREADY;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_BREADY;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_sum_out;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_sum_out_ap_vld;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_din0;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_din1;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_ce;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_din0;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_din1;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_opcode;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_ce;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_done;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_idle;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_ready;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WVALID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WDATA;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WSTRB;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WLAST;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WID;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_RREADY;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_BREADY;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WVALID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WDATA;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WSTRB;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WLAST;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WID;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARVALID;
wire   [63:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARADDR;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARID;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARLEN;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARSIZE;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARBURST;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARLOCK;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARCACHE;
wire   [2:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARPROT;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARQOS;
wire   [3:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARREGION;
wire   [0:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARUSER;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_RREADY;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_BREADY;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_sum_2_out;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_sum_2_out_ap_vld;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_din0;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_din1;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_ce;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_din0;
wire   [31:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_din1;
wire   [1:0] grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_opcode;
wire    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_ce;
wire    BIAS_AWREADY;
wire    BIAS_WREADY;
reg    BIAS_ARVALID;
wire    BIAS_ARREADY;
reg   [63:0] BIAS_ARADDR;
wire    BIAS_RVALID;
reg    BIAS_RREADY;
wire   [31:0] BIAS_RDATA;
wire   [8:0] BIAS_RFIFONUM;
wire    BIAS_BVALID;
wire    INPUT_r_AWREADY;
wire    INPUT_r_WREADY;
reg    INPUT_r_ARVALID;
wire    INPUT_r_ARREADY;
reg   [63:0] INPUT_r_ARADDR;
reg   [31:0] INPUT_r_ARLEN;
wire    INPUT_r_RVALID;
reg    INPUT_r_RREADY;
wire   [31:0] INPUT_r_RDATA;
wire   [8:0] INPUT_r_RFIFONUM;
wire    INPUT_r_BVALID;
reg    OUTPUT_r_AWVALID;
wire    OUTPUT_r_AWREADY;
reg   [63:0] OUTPUT_r_AWADDR;
reg    OUTPUT_r_WVALID;
wire    OUTPUT_r_WREADY;
reg   [31:0] OUTPUT_r_WDATA;
wire    OUTPUT_r_ARREADY;
wire    OUTPUT_r_RVALID;
wire   [31:0] OUTPUT_r_RDATA;
wire   [8:0] OUTPUT_r_RFIFONUM;
wire    OUTPUT_r_BVALID;
reg    OUTPUT_r_BREADY;
wire    WEIGHTS_AWREADY;
wire    WEIGHTS_WREADY;
reg    WEIGHTS_ARVALID;
wire    WEIGHTS_ARREADY;
reg   [63:0] WEIGHTS_ARADDR;
reg   [31:0] WEIGHTS_ARLEN;
wire    WEIGHTS_RVALID;
reg    WEIGHTS_RREADY;
wire   [31:0] WEIGHTS_RDATA;
wire   [8:0] WEIGHTS_RFIFONUM;
wire    WEIGHTS_BVALID;
reg    grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start_reg;
wire    ap_CS_fsm_state11;
reg    grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start_reg;
wire    ap_CS_fsm_state21;
wire  signed [63:0] sext_ln24_fu_281_p1;
wire  signed [63:0] sext_ln32_fu_396_p1;
wire   [0:0] icmp_ln18_fu_299_p2;
wire  signed [63:0] sext_ln32_1_fu_421_p1;
wire  signed [63:0] sext_ln32_2_fu_466_p1;
wire  signed [63:0] sext_ln32_3_fu_491_p1;
wire  signed [63:0] sext_ln24_1_fu_512_p1;
wire  signed [63:0] sext_ln24_2_fu_530_p1;
reg    ap_block_state3_io;
reg    ap_block_state13_io;
reg    ap_block_state22;
wire   [31:0] bitcast_ln32_1_fu_540_p1;
wire   [31:0] bitcast_ln32_3_fu_553_p1;
reg   [3:0] n_fu_128;
wire   [3:0] add_ln18_fu_501_p2;
reg   [31:0] grp_fu_263_p0;
reg   [31:0] grp_fu_263_p1;
wire   [12:0] shl_ln_fu_305_p3;
wire   [8:0] shl_ln24_1_fu_317_p3;
wire   [13:0] zext_ln24_fu_313_p1;
wire   [13:0] zext_ln24_1_fu_325_p1;
wire  signed [13:0] sub_ln24_fu_329_p2;
wire  signed [63:0] sext_ln24_3_fu_335_p1;
wire   [63:0] add_ln24_fu_339_p2;
wire   [13:0] add_ln24_1_fu_354_p2;
wire   [63:0] zext_ln24_2_fu_360_p1;
wire   [5:0] shl_ln1_fu_369_p3;
wire   [63:0] zext_ln32_fu_377_p1;
wire   [63:0] add_ln32_fu_381_p2;
wire   [61:0] trunc_ln1_fu_386_p4;
wire   [63:0] add_ln32_1_fu_406_p2;
wire   [61:0] trunc_ln32_1_fu_411_p4;
wire   [63:0] add_ln24_2_fu_364_p2;
wire   [5:0] or_ln32_fu_441_p2;
wire   [63:0] zext_ln32_1_fu_447_p1;
wire   [63:0] add_ln32_2_fu_451_p2;
wire   [61:0] trunc_ln32_2_fu_456_p4;
wire   [63:0] add_ln32_3_fu_476_p2;
wire   [61:0] trunc_ln32_3_fu_481_p4;
reg    grp_fu_263_ce;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire   [31:0] grp_fu_681_p2;
reg   [31:0] grp_fu_681_p0;
reg   [31:0] grp_fu_681_p1;
reg    grp_fu_681_ce;
reg   [31:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
reg    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'd1;
#0 grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start_reg = 1'b0;
#0 grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start_reg = 1'b0;
#0 n_fu_128 = 4'd0;
end

fc6_hls_fc6_hls_Pipeline_VITIS_LOOP_24_2 grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start),
    .ap_done(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_done),
    .ap_idle(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_idle),
    .ap_ready(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_ready),
    .m_axi_WEIGHTS_AWVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWVALID),
    .m_axi_WEIGHTS_AWREADY(1'b0),
    .m_axi_WEIGHTS_AWADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWADDR),
    .m_axi_WEIGHTS_AWID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWID),
    .m_axi_WEIGHTS_AWLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWLEN),
    .m_axi_WEIGHTS_AWSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWSIZE),
    .m_axi_WEIGHTS_AWBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWBURST),
    .m_axi_WEIGHTS_AWLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWLOCK),
    .m_axi_WEIGHTS_AWCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWCACHE),
    .m_axi_WEIGHTS_AWPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWPROT),
    .m_axi_WEIGHTS_AWQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWQOS),
    .m_axi_WEIGHTS_AWREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWREGION),
    .m_axi_WEIGHTS_AWUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_AWUSER),
    .m_axi_WEIGHTS_WVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WVALID),
    .m_axi_WEIGHTS_WREADY(1'b0),
    .m_axi_WEIGHTS_WDATA(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WDATA),
    .m_axi_WEIGHTS_WSTRB(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WSTRB),
    .m_axi_WEIGHTS_WLAST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WLAST),
    .m_axi_WEIGHTS_WID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WID),
    .m_axi_WEIGHTS_WUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_WUSER),
    .m_axi_WEIGHTS_ARVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARVALID),
    .m_axi_WEIGHTS_ARREADY(WEIGHTS_ARREADY),
    .m_axi_WEIGHTS_ARADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARADDR),
    .m_axi_WEIGHTS_ARID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARID),
    .m_axi_WEIGHTS_ARLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARLEN),
    .m_axi_WEIGHTS_ARSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARSIZE),
    .m_axi_WEIGHTS_ARBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARBURST),
    .m_axi_WEIGHTS_ARLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARLOCK),
    .m_axi_WEIGHTS_ARCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARCACHE),
    .m_axi_WEIGHTS_ARPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARPROT),
    .m_axi_WEIGHTS_ARQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARQOS),
    .m_axi_WEIGHTS_ARREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARREGION),
    .m_axi_WEIGHTS_ARUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARUSER),
    .m_axi_WEIGHTS_RVALID(WEIGHTS_RVALID),
    .m_axi_WEIGHTS_RREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_RREADY),
    .m_axi_WEIGHTS_RDATA(WEIGHTS_RDATA),
    .m_axi_WEIGHTS_RLAST(1'b0),
    .m_axi_WEIGHTS_RID(1'd0),
    .m_axi_WEIGHTS_RFIFONUM(WEIGHTS_RFIFONUM),
    .m_axi_WEIGHTS_RUSER(1'd0),
    .m_axi_WEIGHTS_RRESP(2'd0),
    .m_axi_WEIGHTS_BVALID(1'b0),
    .m_axi_WEIGHTS_BREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_BREADY),
    .m_axi_WEIGHTS_BRESP(2'd0),
    .m_axi_WEIGHTS_BID(1'd0),
    .m_axi_WEIGHTS_BUSER(1'd0),
    .m_axi_INPUT_r_AWVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWVALID),
    .m_axi_INPUT_r_AWREADY(1'b0),
    .m_axi_INPUT_r_AWADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWADDR),
    .m_axi_INPUT_r_AWID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWID),
    .m_axi_INPUT_r_AWLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWLEN),
    .m_axi_INPUT_r_AWSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWSIZE),
    .m_axi_INPUT_r_AWBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWBURST),
    .m_axi_INPUT_r_AWLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWLOCK),
    .m_axi_INPUT_r_AWCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWCACHE),
    .m_axi_INPUT_r_AWPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWPROT),
    .m_axi_INPUT_r_AWQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWQOS),
    .m_axi_INPUT_r_AWREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWREGION),
    .m_axi_INPUT_r_AWUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_AWUSER),
    .m_axi_INPUT_r_WVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WVALID),
    .m_axi_INPUT_r_WREADY(1'b0),
    .m_axi_INPUT_r_WDATA(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WDATA),
    .m_axi_INPUT_r_WSTRB(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WSTRB),
    .m_axi_INPUT_r_WLAST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WLAST),
    .m_axi_INPUT_r_WID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WID),
    .m_axi_INPUT_r_WUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_WUSER),
    .m_axi_INPUT_r_ARVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARVALID),
    .m_axi_INPUT_r_ARREADY(INPUT_r_ARREADY),
    .m_axi_INPUT_r_ARADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARADDR),
    .m_axi_INPUT_r_ARID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARID),
    .m_axi_INPUT_r_ARLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARLEN),
    .m_axi_INPUT_r_ARSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARSIZE),
    .m_axi_INPUT_r_ARBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARBURST),
    .m_axi_INPUT_r_ARLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARLOCK),
    .m_axi_INPUT_r_ARCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARCACHE),
    .m_axi_INPUT_r_ARPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARPROT),
    .m_axi_INPUT_r_ARQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARQOS),
    .m_axi_INPUT_r_ARREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARREGION),
    .m_axi_INPUT_r_ARUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARUSER),
    .m_axi_INPUT_r_RVALID(INPUT_r_RVALID),
    .m_axi_INPUT_r_RREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_RREADY),
    .m_axi_INPUT_r_RDATA(INPUT_r_RDATA),
    .m_axi_INPUT_r_RLAST(1'b0),
    .m_axi_INPUT_r_RID(1'd0),
    .m_axi_INPUT_r_RFIFONUM(INPUT_r_RFIFONUM),
    .m_axi_INPUT_r_RUSER(1'd0),
    .m_axi_INPUT_r_RRESP(2'd0),
    .m_axi_INPUT_r_BVALID(1'b0),
    .m_axi_INPUT_r_BREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_BREADY),
    .m_axi_INPUT_r_BRESP(2'd0),
    .m_axi_INPUT_r_BID(1'd0),
    .m_axi_INPUT_r_BUSER(1'd0),
    .sext_ln24(trunc_ln_reg_595),
    .sext_ln24_1(trunc_ln24_1_reg_609),
    .sum_out(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_sum_out),
    .sum_out_ap_vld(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_sum_out_ap_vld),
    .grp_fu_681_p_din0(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_din0),
    .grp_fu_681_p_din1(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_din1),
    .grp_fu_681_p_dout0(grp_fu_681_p2),
    .grp_fu_681_p_ce(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_ce),
    .grp_fu_263_p_din0(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_din0),
    .grp_fu_263_p_din1(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_din1),
    .grp_fu_263_p_opcode(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_opcode),
    .grp_fu_263_p_dout0(grp_fu_263_p2),
    .grp_fu_263_p_ce(grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_ce)
);

fc6_hls_fc6_hls_Pipeline_VITIS_LOOP_24_21 grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start),
    .ap_done(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_done),
    .ap_idle(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_idle),
    .ap_ready(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_ready),
    .m_axi_WEIGHTS_AWVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWVALID),
    .m_axi_WEIGHTS_AWREADY(1'b0),
    .m_axi_WEIGHTS_AWADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWADDR),
    .m_axi_WEIGHTS_AWID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWID),
    .m_axi_WEIGHTS_AWLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWLEN),
    .m_axi_WEIGHTS_AWSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWSIZE),
    .m_axi_WEIGHTS_AWBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWBURST),
    .m_axi_WEIGHTS_AWLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWLOCK),
    .m_axi_WEIGHTS_AWCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWCACHE),
    .m_axi_WEIGHTS_AWPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWPROT),
    .m_axi_WEIGHTS_AWQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWQOS),
    .m_axi_WEIGHTS_AWREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWREGION),
    .m_axi_WEIGHTS_AWUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_AWUSER),
    .m_axi_WEIGHTS_WVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WVALID),
    .m_axi_WEIGHTS_WREADY(1'b0),
    .m_axi_WEIGHTS_WDATA(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WDATA),
    .m_axi_WEIGHTS_WSTRB(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WSTRB),
    .m_axi_WEIGHTS_WLAST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WLAST),
    .m_axi_WEIGHTS_WID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WID),
    .m_axi_WEIGHTS_WUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_WUSER),
    .m_axi_WEIGHTS_ARVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARVALID),
    .m_axi_WEIGHTS_ARREADY(WEIGHTS_ARREADY),
    .m_axi_WEIGHTS_ARADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARADDR),
    .m_axi_WEIGHTS_ARID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARID),
    .m_axi_WEIGHTS_ARLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARLEN),
    .m_axi_WEIGHTS_ARSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARSIZE),
    .m_axi_WEIGHTS_ARBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARBURST),
    .m_axi_WEIGHTS_ARLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARLOCK),
    .m_axi_WEIGHTS_ARCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARCACHE),
    .m_axi_WEIGHTS_ARPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARPROT),
    .m_axi_WEIGHTS_ARQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARQOS),
    .m_axi_WEIGHTS_ARREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARREGION),
    .m_axi_WEIGHTS_ARUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARUSER),
    .m_axi_WEIGHTS_RVALID(WEIGHTS_RVALID),
    .m_axi_WEIGHTS_RREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_RREADY),
    .m_axi_WEIGHTS_RDATA(WEIGHTS_RDATA),
    .m_axi_WEIGHTS_RLAST(1'b0),
    .m_axi_WEIGHTS_RID(1'd0),
    .m_axi_WEIGHTS_RFIFONUM(WEIGHTS_RFIFONUM),
    .m_axi_WEIGHTS_RUSER(1'd0),
    .m_axi_WEIGHTS_RRESP(2'd0),
    .m_axi_WEIGHTS_BVALID(1'b0),
    .m_axi_WEIGHTS_BREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_BREADY),
    .m_axi_WEIGHTS_BRESP(2'd0),
    .m_axi_WEIGHTS_BID(1'd0),
    .m_axi_WEIGHTS_BUSER(1'd0),
    .m_axi_INPUT_r_AWVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWVALID),
    .m_axi_INPUT_r_AWREADY(1'b0),
    .m_axi_INPUT_r_AWADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWADDR),
    .m_axi_INPUT_r_AWID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWID),
    .m_axi_INPUT_r_AWLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWLEN),
    .m_axi_INPUT_r_AWSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWSIZE),
    .m_axi_INPUT_r_AWBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWBURST),
    .m_axi_INPUT_r_AWLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWLOCK),
    .m_axi_INPUT_r_AWCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWCACHE),
    .m_axi_INPUT_r_AWPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWPROT),
    .m_axi_INPUT_r_AWQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWQOS),
    .m_axi_INPUT_r_AWREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWREGION),
    .m_axi_INPUT_r_AWUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_AWUSER),
    .m_axi_INPUT_r_WVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WVALID),
    .m_axi_INPUT_r_WREADY(1'b0),
    .m_axi_INPUT_r_WDATA(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WDATA),
    .m_axi_INPUT_r_WSTRB(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WSTRB),
    .m_axi_INPUT_r_WLAST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WLAST),
    .m_axi_INPUT_r_WID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WID),
    .m_axi_INPUT_r_WUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_WUSER),
    .m_axi_INPUT_r_ARVALID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARVALID),
    .m_axi_INPUT_r_ARREADY(INPUT_r_ARREADY),
    .m_axi_INPUT_r_ARADDR(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARADDR),
    .m_axi_INPUT_r_ARID(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARID),
    .m_axi_INPUT_r_ARLEN(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARLEN),
    .m_axi_INPUT_r_ARSIZE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARSIZE),
    .m_axi_INPUT_r_ARBURST(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARBURST),
    .m_axi_INPUT_r_ARLOCK(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARLOCK),
    .m_axi_INPUT_r_ARCACHE(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARCACHE),
    .m_axi_INPUT_r_ARPROT(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARPROT),
    .m_axi_INPUT_r_ARQOS(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARQOS),
    .m_axi_INPUT_r_ARREGION(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARREGION),
    .m_axi_INPUT_r_ARUSER(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARUSER),
    .m_axi_INPUT_r_RVALID(INPUT_r_RVALID),
    .m_axi_INPUT_r_RREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_RREADY),
    .m_axi_INPUT_r_RDATA(INPUT_r_RDATA),
    .m_axi_INPUT_r_RLAST(1'b0),
    .m_axi_INPUT_r_RID(1'd0),
    .m_axi_INPUT_r_RFIFONUM(INPUT_r_RFIFONUM),
    .m_axi_INPUT_r_RUSER(1'd0),
    .m_axi_INPUT_r_RRESP(2'd0),
    .m_axi_INPUT_r_BVALID(1'b0),
    .m_axi_INPUT_r_BREADY(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_BREADY),
    .m_axi_INPUT_r_BRESP(2'd0),
    .m_axi_INPUT_r_BID(1'd0),
    .m_axi_INPUT_r_BUSER(1'd0),
    .sext_ln24(trunc_ln_reg_595),
    .sext_ln24_2(trunc_ln24_2_reg_627),
    .sum_2_out(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_sum_2_out),
    .sum_2_out_ap_vld(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_sum_2_out_ap_vld),
    .grp_fu_681_p_din0(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_din0),
    .grp_fu_681_p_din1(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_din1),
    .grp_fu_681_p_dout0(grp_fu_681_p2),
    .grp_fu_681_p_ce(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_ce),
    .grp_fu_263_p_din0(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_din0),
    .grp_fu_263_p_din1(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_din1),
    .grp_fu_263_p_opcode(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_opcode),
    .grp_fu_263_p_dout0(grp_fu_263_p2),
    .grp_fu_263_p_ce(grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_ce)
);

fc6_hls_CTRL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_BUS_DATA_WIDTH ))
CTRL_BUS_s_axi_U(
    .AWVALID(s_axi_CTRL_BUS_AWVALID),
    .AWREADY(s_axi_CTRL_BUS_AWREADY),
    .AWADDR(s_axi_CTRL_BUS_AWADDR),
    .WVALID(s_axi_CTRL_BUS_WVALID),
    .WREADY(s_axi_CTRL_BUS_WREADY),
    .WDATA(s_axi_CTRL_BUS_WDATA),
    .WSTRB(s_axi_CTRL_BUS_WSTRB),
    .ARVALID(s_axi_CTRL_BUS_ARVALID),
    .ARREADY(s_axi_CTRL_BUS_ARREADY),
    .ARADDR(s_axi_CTRL_BUS_ARADDR),
    .RVALID(s_axi_CTRL_BUS_RVALID),
    .RREADY(s_axi_CTRL_BUS_RREADY),
    .RDATA(s_axi_CTRL_BUS_RDATA),
    .RRESP(s_axi_CTRL_BUS_RRESP),
    .BVALID(s_axi_CTRL_BUS_BVALID),
    .BREADY(s_axi_CTRL_BUS_BREADY),
    .BRESP(s_axi_CTRL_BUS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fc6_hls_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r_r(input_r_r),
    .weights_r(weights_r),
    .bias_r(bias_r),
    .output_r_r(output_r_r)
);

fc6_hls_BIAS_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_BIAS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_BIAS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_BIAS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_BIAS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_BIAS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_BIAS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_BIAS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_BIAS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_BIAS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_BIAS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_BIAS_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
BIAS_m_axi_U(
    .AWVALID(m_axi_BIAS_AWVALID),
    .AWREADY(m_axi_BIAS_AWREADY),
    .AWADDR(m_axi_BIAS_AWADDR),
    .AWID(m_axi_BIAS_AWID),
    .AWLEN(m_axi_BIAS_AWLEN),
    .AWSIZE(m_axi_BIAS_AWSIZE),
    .AWBURST(m_axi_BIAS_AWBURST),
    .AWLOCK(m_axi_BIAS_AWLOCK),
    .AWCACHE(m_axi_BIAS_AWCACHE),
    .AWPROT(m_axi_BIAS_AWPROT),
    .AWQOS(m_axi_BIAS_AWQOS),
    .AWREGION(m_axi_BIAS_AWREGION),
    .AWUSER(m_axi_BIAS_AWUSER),
    .WVALID(m_axi_BIAS_WVALID),
    .WREADY(m_axi_BIAS_WREADY),
    .WDATA(m_axi_BIAS_WDATA),
    .WSTRB(m_axi_BIAS_WSTRB),
    .WLAST(m_axi_BIAS_WLAST),
    .WID(m_axi_BIAS_WID),
    .WUSER(m_axi_BIAS_WUSER),
    .ARVALID(m_axi_BIAS_ARVALID),
    .ARREADY(m_axi_BIAS_ARREADY),
    .ARADDR(m_axi_BIAS_ARADDR),
    .ARID(m_axi_BIAS_ARID),
    .ARLEN(m_axi_BIAS_ARLEN),
    .ARSIZE(m_axi_BIAS_ARSIZE),
    .ARBURST(m_axi_BIAS_ARBURST),
    .ARLOCK(m_axi_BIAS_ARLOCK),
    .ARCACHE(m_axi_BIAS_ARCACHE),
    .ARPROT(m_axi_BIAS_ARPROT),
    .ARQOS(m_axi_BIAS_ARQOS),
    .ARREGION(m_axi_BIAS_ARREGION),
    .ARUSER(m_axi_BIAS_ARUSER),
    .RVALID(m_axi_BIAS_RVALID),
    .RREADY(m_axi_BIAS_RREADY),
    .RDATA(m_axi_BIAS_RDATA),
    .RLAST(m_axi_BIAS_RLAST),
    .RID(m_axi_BIAS_RID),
    .RUSER(m_axi_BIAS_RUSER),
    .RRESP(m_axi_BIAS_RRESP),
    .BVALID(m_axi_BIAS_BVALID),
    .BREADY(m_axi_BIAS_BREADY),
    .BRESP(m_axi_BIAS_BRESP),
    .BID(m_axi_BIAS_BID),
    .BUSER(m_axi_BIAS_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(BIAS_ARVALID),
    .I_ARREADY(BIAS_ARREADY),
    .I_ARADDR(BIAS_ARADDR),
    .I_ARLEN(32'd1),
    .I_RVALID(BIAS_RVALID),
    .I_RREADY(BIAS_RREADY),
    .I_RDATA(BIAS_RDATA),
    .I_RFIFONUM(BIAS_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(BIAS_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(BIAS_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(BIAS_BVALID),
    .I_BREADY(1'b0)
);

fc6_hls_INPUT_r_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_INPUT_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_INPUT_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_INPUT_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_INPUT_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_INPUT_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_INPUT_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_INPUT_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_INPUT_R_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_INPUT_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_INPUT_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_INPUT_R_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
INPUT_r_m_axi_U(
    .AWVALID(m_axi_INPUT_r_AWVALID),
    .AWREADY(m_axi_INPUT_r_AWREADY),
    .AWADDR(m_axi_INPUT_r_AWADDR),
    .AWID(m_axi_INPUT_r_AWID),
    .AWLEN(m_axi_INPUT_r_AWLEN),
    .AWSIZE(m_axi_INPUT_r_AWSIZE),
    .AWBURST(m_axi_INPUT_r_AWBURST),
    .AWLOCK(m_axi_INPUT_r_AWLOCK),
    .AWCACHE(m_axi_INPUT_r_AWCACHE),
    .AWPROT(m_axi_INPUT_r_AWPROT),
    .AWQOS(m_axi_INPUT_r_AWQOS),
    .AWREGION(m_axi_INPUT_r_AWREGION),
    .AWUSER(m_axi_INPUT_r_AWUSER),
    .WVALID(m_axi_INPUT_r_WVALID),
    .WREADY(m_axi_INPUT_r_WREADY),
    .WDATA(m_axi_INPUT_r_WDATA),
    .WSTRB(m_axi_INPUT_r_WSTRB),
    .WLAST(m_axi_INPUT_r_WLAST),
    .WID(m_axi_INPUT_r_WID),
    .WUSER(m_axi_INPUT_r_WUSER),
    .ARVALID(m_axi_INPUT_r_ARVALID),
    .ARREADY(m_axi_INPUT_r_ARREADY),
    .ARADDR(m_axi_INPUT_r_ARADDR),
    .ARID(m_axi_INPUT_r_ARID),
    .ARLEN(m_axi_INPUT_r_ARLEN),
    .ARSIZE(m_axi_INPUT_r_ARSIZE),
    .ARBURST(m_axi_INPUT_r_ARBURST),
    .ARLOCK(m_axi_INPUT_r_ARLOCK),
    .ARCACHE(m_axi_INPUT_r_ARCACHE),
    .ARPROT(m_axi_INPUT_r_ARPROT),
    .ARQOS(m_axi_INPUT_r_ARQOS),
    .ARREGION(m_axi_INPUT_r_ARREGION),
    .ARUSER(m_axi_INPUT_r_ARUSER),
    .RVALID(m_axi_INPUT_r_RVALID),
    .RREADY(m_axi_INPUT_r_RREADY),
    .RDATA(m_axi_INPUT_r_RDATA),
    .RLAST(m_axi_INPUT_r_RLAST),
    .RID(m_axi_INPUT_r_RID),
    .RUSER(m_axi_INPUT_r_RUSER),
    .RRESP(m_axi_INPUT_r_RRESP),
    .BVALID(m_axi_INPUT_r_BVALID),
    .BREADY(m_axi_INPUT_r_BREADY),
    .BRESP(m_axi_INPUT_r_BRESP),
    .BID(m_axi_INPUT_r_BID),
    .BUSER(m_axi_INPUT_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(INPUT_r_ARVALID),
    .I_ARREADY(INPUT_r_ARREADY),
    .I_ARADDR(INPUT_r_ARADDR),
    .I_ARLEN(INPUT_r_ARLEN),
    .I_RVALID(INPUT_r_RVALID),
    .I_RREADY(INPUT_r_RREADY),
    .I_RDATA(INPUT_r_RDATA),
    .I_RFIFONUM(INPUT_r_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(INPUT_r_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(INPUT_r_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(INPUT_r_BVALID),
    .I_BREADY(1'b0)
);

fc6_hls_OUTPUT_r_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUTPUT_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUTPUT_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUTPUT_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUTPUT_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUTPUT_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUTPUT_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUTPUT_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUTPUT_R_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_OUTPUT_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUTPUT_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUTPUT_R_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
OUTPUT_r_m_axi_U(
    .AWVALID(m_axi_OUTPUT_r_AWVALID),
    .AWREADY(m_axi_OUTPUT_r_AWREADY),
    .AWADDR(m_axi_OUTPUT_r_AWADDR),
    .AWID(m_axi_OUTPUT_r_AWID),
    .AWLEN(m_axi_OUTPUT_r_AWLEN),
    .AWSIZE(m_axi_OUTPUT_r_AWSIZE),
    .AWBURST(m_axi_OUTPUT_r_AWBURST),
    .AWLOCK(m_axi_OUTPUT_r_AWLOCK),
    .AWCACHE(m_axi_OUTPUT_r_AWCACHE),
    .AWPROT(m_axi_OUTPUT_r_AWPROT),
    .AWQOS(m_axi_OUTPUT_r_AWQOS),
    .AWREGION(m_axi_OUTPUT_r_AWREGION),
    .AWUSER(m_axi_OUTPUT_r_AWUSER),
    .WVALID(m_axi_OUTPUT_r_WVALID),
    .WREADY(m_axi_OUTPUT_r_WREADY),
    .WDATA(m_axi_OUTPUT_r_WDATA),
    .WSTRB(m_axi_OUTPUT_r_WSTRB),
    .WLAST(m_axi_OUTPUT_r_WLAST),
    .WID(m_axi_OUTPUT_r_WID),
    .WUSER(m_axi_OUTPUT_r_WUSER),
    .ARVALID(m_axi_OUTPUT_r_ARVALID),
    .ARREADY(m_axi_OUTPUT_r_ARREADY),
    .ARADDR(m_axi_OUTPUT_r_ARADDR),
    .ARID(m_axi_OUTPUT_r_ARID),
    .ARLEN(m_axi_OUTPUT_r_ARLEN),
    .ARSIZE(m_axi_OUTPUT_r_ARSIZE),
    .ARBURST(m_axi_OUTPUT_r_ARBURST),
    .ARLOCK(m_axi_OUTPUT_r_ARLOCK),
    .ARCACHE(m_axi_OUTPUT_r_ARCACHE),
    .ARPROT(m_axi_OUTPUT_r_ARPROT),
    .ARQOS(m_axi_OUTPUT_r_ARQOS),
    .ARREGION(m_axi_OUTPUT_r_ARREGION),
    .ARUSER(m_axi_OUTPUT_r_ARUSER),
    .RVALID(m_axi_OUTPUT_r_RVALID),
    .RREADY(m_axi_OUTPUT_r_RREADY),
    .RDATA(m_axi_OUTPUT_r_RDATA),
    .RLAST(m_axi_OUTPUT_r_RLAST),
    .RID(m_axi_OUTPUT_r_RID),
    .RUSER(m_axi_OUTPUT_r_RUSER),
    .RRESP(m_axi_OUTPUT_r_RRESP),
    .BVALID(m_axi_OUTPUT_r_BVALID),
    .BREADY(m_axi_OUTPUT_r_BREADY),
    .BRESP(m_axi_OUTPUT_r_BRESP),
    .BID(m_axi_OUTPUT_r_BID),
    .BUSER(m_axi_OUTPUT_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(OUTPUT_r_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARLEN(32'd0),
    .I_RVALID(OUTPUT_r_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(OUTPUT_r_RDATA),
    .I_RFIFONUM(OUTPUT_r_RFIFONUM),
    .I_AWVALID(OUTPUT_r_AWVALID),
    .I_AWREADY(OUTPUT_r_AWREADY),
    .I_AWADDR(OUTPUT_r_AWADDR),
    .I_AWLEN(32'd1),
    .I_WVALID(OUTPUT_r_WVALID),
    .I_WREADY(OUTPUT_r_WREADY),
    .I_WDATA(OUTPUT_r_WDATA),
    .I_WSTRB(4'd15),
    .I_BVALID(OUTPUT_r_BVALID),
    .I_BREADY(OUTPUT_r_BREADY)
);

fc6_hls_WEIGHTS_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_WEIGHTS_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_WEIGHTS_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_WEIGHTS_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_WEIGHTS_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_WEIGHTS_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_WEIGHTS_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_WEIGHTS_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_WEIGHTS_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_WEIGHTS_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_WEIGHTS_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_WEIGHTS_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
WEIGHTS_m_axi_U(
    .AWVALID(m_axi_WEIGHTS_AWVALID),
    .AWREADY(m_axi_WEIGHTS_AWREADY),
    .AWADDR(m_axi_WEIGHTS_AWADDR),
    .AWID(m_axi_WEIGHTS_AWID),
    .AWLEN(m_axi_WEIGHTS_AWLEN),
    .AWSIZE(m_axi_WEIGHTS_AWSIZE),
    .AWBURST(m_axi_WEIGHTS_AWBURST),
    .AWLOCK(m_axi_WEIGHTS_AWLOCK),
    .AWCACHE(m_axi_WEIGHTS_AWCACHE),
    .AWPROT(m_axi_WEIGHTS_AWPROT),
    .AWQOS(m_axi_WEIGHTS_AWQOS),
    .AWREGION(m_axi_WEIGHTS_AWREGION),
    .AWUSER(m_axi_WEIGHTS_AWUSER),
    .WVALID(m_axi_WEIGHTS_WVALID),
    .WREADY(m_axi_WEIGHTS_WREADY),
    .WDATA(m_axi_WEIGHTS_WDATA),
    .WSTRB(m_axi_WEIGHTS_WSTRB),
    .WLAST(m_axi_WEIGHTS_WLAST),
    .WID(m_axi_WEIGHTS_WID),
    .WUSER(m_axi_WEIGHTS_WUSER),
    .ARVALID(m_axi_WEIGHTS_ARVALID),
    .ARREADY(m_axi_WEIGHTS_ARREADY),
    .ARADDR(m_axi_WEIGHTS_ARADDR),
    .ARID(m_axi_WEIGHTS_ARID),
    .ARLEN(m_axi_WEIGHTS_ARLEN),
    .ARSIZE(m_axi_WEIGHTS_ARSIZE),
    .ARBURST(m_axi_WEIGHTS_ARBURST),
    .ARLOCK(m_axi_WEIGHTS_ARLOCK),
    .ARCACHE(m_axi_WEIGHTS_ARCACHE),
    .ARPROT(m_axi_WEIGHTS_ARPROT),
    .ARQOS(m_axi_WEIGHTS_ARQOS),
    .ARREGION(m_axi_WEIGHTS_ARREGION),
    .ARUSER(m_axi_WEIGHTS_ARUSER),
    .RVALID(m_axi_WEIGHTS_RVALID),
    .RREADY(m_axi_WEIGHTS_RREADY),
    .RDATA(m_axi_WEIGHTS_RDATA),
    .RLAST(m_axi_WEIGHTS_RLAST),
    .RID(m_axi_WEIGHTS_RID),
    .RUSER(m_axi_WEIGHTS_RUSER),
    .RRESP(m_axi_WEIGHTS_RRESP),
    .BVALID(m_axi_WEIGHTS_BVALID),
    .BREADY(m_axi_WEIGHTS_BREADY),
    .BRESP(m_axi_WEIGHTS_BRESP),
    .BID(m_axi_WEIGHTS_BID),
    .BUSER(m_axi_WEIGHTS_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(WEIGHTS_ARVALID),
    .I_ARREADY(WEIGHTS_ARREADY),
    .I_ARADDR(WEIGHTS_ARADDR),
    .I_ARLEN(WEIGHTS_ARLEN),
    .I_RVALID(WEIGHTS_RVALID),
    .I_RREADY(WEIGHTS_RREADY),
    .I_RDATA(WEIGHTS_RDATA),
    .I_RFIFONUM(WEIGHTS_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(WEIGHTS_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(WEIGHTS_WREADY),
    .I_WDATA(32'd0),
    .I_WSTRB(4'd0),
    .I_BVALID(WEIGHTS_BVALID),
    .I_BREADY(1'b0)
);

fc6_hls_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U15(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_263_p0),
    .din1(grp_fu_263_p1),
    .ce(grp_fu_263_ce),
    .dout(grp_fu_263_p2)
);

fc6_hls_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_681_p0),
    .din1(grp_fu_681_p1),
    .ce(grp_fu_681_ce),
    .dout(grp_fu_681_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state21)) begin
            grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start_reg <= 1'b1;
        end else if ((grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_ready == 1'b1)) begin
            grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start_reg <= 1'b1;
        end else if ((grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_ready == 1'b1)) begin
            grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        n_fu_128 <= 4'd0;
    end else if (((icmp_ln18_fu_299_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        n_fu_128 <= add_ln18_fu_501_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        BIAS_addr_1_read_reg_668 <= BIAS_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        BIAS_addr_1_reg_633 <= sext_ln32_2_fu_466_p1;
        BIAS_addr_reg_615 <= sext_ln32_fu_396_p1;
        OUTPUT_r_addr_1_reg_639 <= sext_ln32_3_fu_491_p1;
        OUTPUT_r_addr_reg_621 <= sext_ln32_1_fu_421_p1;
        trunc_ln24_1_reg_609 <= {{add_ln24_fu_339_p2[63:2]}};
        trunc_ln24_2_reg_627 <= {{add_ln24_2_fu_364_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        BIAS_addr_read_reg_650 <= BIAS_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        INPUT_r_addr_reg_601 <= sext_ln24_fu_281_p1;
        bias_read_reg_571 <= bias_r;
        output_r_read_reg_565 <= output_r_r;
        trunc_ln_reg_595 <= {{input_r_r[63:2]}};
        weights_read_reg_577 <= weights_r;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_267 <= grp_fu_263_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13))) begin
        BIAS_ARADDR = BIAS_addr_1_reg_633;
    end else if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        BIAS_ARADDR = BIAS_addr_reg_615;
    end else begin
        BIAS_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)))) begin
        BIAS_ARVALID = 1'b1;
    end else begin
        BIAS_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((~((grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_done == 1'b0) | (1'b0 == BIAS_RVALID)) & (1'b1 == ap_CS_fsm_state12)) | (~((1'b1 == ap_block_state22) | (grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state22)))) begin
        BIAS_RREADY = 1'b1;
    end else begin
        BIAS_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state3))) begin
        BIAS_blk_n_AR = m_axi_BIAS_ARREADY;
    end else begin
        BIAS_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state12))) begin
        BIAS_blk_n_R = m_axi_BIAS_RVALID;
    end else begin
        BIAS_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)))) begin
        INPUT_r_ARADDR = INPUT_r_addr_reg_601;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        INPUT_r_ARADDR = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        INPUT_r_ARADDR = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARADDR;
    end else begin
        INPUT_r_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)))) begin
        INPUT_r_ARLEN = 32'd120;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        INPUT_r_ARLEN = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        INPUT_r_ARLEN = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARLEN;
    end else begin
        INPUT_r_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)))) begin
        INPUT_r_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        INPUT_r_ARVALID = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        INPUT_r_ARVALID = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_ARVALID;
    end else begin
        INPUT_r_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        INPUT_r_RREADY = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_INPUT_r_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        INPUT_r_RREADY = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_INPUT_r_RREADY;
    end else begin
        INPUT_r_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state3))) begin
        INPUT_r_blk_n_AR = m_axi_INPUT_r_ARREADY;
    end else begin
        INPUT_r_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == OUTPUT_r_AWREADY) & (1'b1 == ap_CS_fsm_state4))) begin
        OUTPUT_r_AWADDR = OUTPUT_r_addr_1_reg_639;
    end else if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        OUTPUT_r_AWADDR = OUTPUT_r_addr_reg_621;
    end else begin
        OUTPUT_r_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == OUTPUT_r_AWREADY) & (1'b1 == ap_CS_fsm_state4)))) begin
        OUTPUT_r_AWVALID = 1'b1;
    end else begin
        OUTPUT_r_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == OUTPUT_r_BVALID) & (1'b1 == ap_CS_fsm_state32)) | (~((1'b1 == ap_block_state22) | (grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state22)))) begin
        OUTPUT_r_BREADY = 1'b1;
    end else begin
        OUTPUT_r_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        OUTPUT_r_WDATA = bitcast_ln32_3_fu_553_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        OUTPUT_r_WDATA = bitcast_ln32_1_fu_540_p1;
    end else begin
        OUTPUT_r_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == OUTPUT_r_WREADY) & (1'b1 == ap_CS_fsm_state27)) | ((1'b1 == OUTPUT_r_WREADY) & (1'b1 == ap_CS_fsm_state17)))) begin
        OUTPUT_r_WVALID = 1'b1;
    end else begin
        OUTPUT_r_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        OUTPUT_r_blk_n_AW = m_axi_OUTPUT_r_AWREADY;
    end else begin
        OUTPUT_r_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state22))) begin
        OUTPUT_r_blk_n_B = m_axi_OUTPUT_r_BVALID;
    end else begin
        OUTPUT_r_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state17))) begin
        OUTPUT_r_blk_n_W = m_axi_OUTPUT_r_WREADY;
    end else begin
        OUTPUT_r_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13))) begin
        WEIGHTS_ARADDR = sext_ln24_2_fu_530_p1;
    end else if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        WEIGHTS_ARADDR = sext_ln24_1_fu_512_p1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        WEIGHTS_ARADDR = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        WEIGHTS_ARADDR = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARADDR;
    end else begin
        WEIGHTS_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)))) begin
        WEIGHTS_ARLEN = 32'd120;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        WEIGHTS_ARLEN = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        WEIGHTS_ARLEN = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARLEN;
    end else begin
        WEIGHTS_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)) | ((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3)))) begin
        WEIGHTS_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        WEIGHTS_ARVALID = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        WEIGHTS_ARVALID = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_ARVALID;
    end else begin
        WEIGHTS_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state22))) begin
        WEIGHTS_RREADY = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_m_axi_WEIGHTS_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        WEIGHTS_RREADY = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_m_axi_WEIGHTS_RREADY;
    end else begin
        WEIGHTS_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state3))) begin
        WEIGHTS_blk_n_AR = m_axi_WEIGHTS_ARREADY;
    end else begin
        WEIGHTS_blk_n_AR = 1'b1;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if (((grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_done == 1'b0) | (1'b0 == BIAS_RVALID))) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state13_io)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == OUTPUT_r_WREADY)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state22) | (grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_done == 1'b0))) begin
        ap_ST_fsm_state22_blk = 1'b1;
    end else begin
        ap_ST_fsm_state22_blk = 1'b0;
    end
end

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == OUTPUT_r_WREADY)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((1'b0 == OUTPUT_r_BVALID)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_io)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == OUTPUT_r_AWREADY)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln18_fu_299_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln18_fu_299_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_263_ce = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_263_ce = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_ce;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | ((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13)))) begin
        grp_fu_263_ce = 1'b1;
    end else begin
        grp_fu_263_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_263_p0 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_263_p0 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_263_p0 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_sum_2_out;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_263_p0 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_sum_out;
    end else begin
        grp_fu_263_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_263_p1 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_263_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_263_p1 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_263_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        grp_fu_263_p1 = bitcast_ln32_2_fu_549_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_263_p1 = bitcast_ln32_fu_526_p1;
    end else begin
        grp_fu_263_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_681_ce = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_681_ce = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_ce;
    end else begin
        grp_fu_681_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_681_p0 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_681_p0 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_din0;
    end else begin
        grp_fu_681_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_681_p1 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_grp_fu_681_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_681_p1 = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_grp_fu_681_p_din1;
    end else begin
        grp_fu_681_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln18_fu_299_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == OUTPUT_r_AWREADY) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if ((~((grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_done == 1'b0) | (1'b0 == BIAS_RVALID)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((1'b0 == ap_block_state13_io) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((1'b1 == OUTPUT_r_WREADY) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if ((~((1'b1 == ap_block_state22) | (grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state22))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == OUTPUT_r_WREADY) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((1'b1 == OUTPUT_r_BVALID) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln18_fu_501_p2 = (n_fu_128 + 4'd2);

assign add_ln24_1_fu_354_p2 = ($signed(sub_ln24_fu_329_p2) + $signed(14'd480));

assign add_ln24_2_fu_364_p2 = (zext_ln24_2_fu_360_p1 + weights_read_reg_577);

assign add_ln24_fu_339_p2 = ($signed(sext_ln24_3_fu_335_p1) + $signed(weights_read_reg_577));

assign add_ln32_1_fu_406_p2 = (zext_ln32_fu_377_p1 + output_r_read_reg_565);

assign add_ln32_2_fu_451_p2 = (zext_ln32_1_fu_447_p1 + bias_read_reg_571);

assign add_ln32_3_fu_476_p2 = (zext_ln32_1_fu_447_p1 + output_r_read_reg_565);

assign add_ln32_fu_381_p2 = (zext_ln32_fu_377_p1 + bias_read_reg_571);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state13_io = ((1'b0 == WEIGHTS_ARREADY) | (1'b0 == INPUT_r_ARREADY) | (1'b0 == BIAS_ARREADY));
end

always @ (*) begin
    ap_block_state22 = ((1'b0 == OUTPUT_r_BVALID) | (1'b0 == BIAS_RVALID));
end

always @ (*) begin
    ap_block_state3_io = ((1'b0 == WEIGHTS_ARREADY) | (1'b0 == OUTPUT_r_AWREADY) | (1'b0 == INPUT_r_ARREADY) | (1'b0 == BIAS_ARREADY));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln32_1_fu_540_p1 = reg_267;

assign bitcast_ln32_2_fu_549_p1 = BIAS_addr_1_read_reg_668;

assign bitcast_ln32_3_fu_553_p1 = reg_267;

assign bitcast_ln32_fu_526_p1 = BIAS_addr_read_reg_650;

assign grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start = grp_fc6_hls_Pipeline_VITIS_LOOP_24_21_fu_252_ap_start_reg;

assign grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start = grp_fc6_hls_Pipeline_VITIS_LOOP_24_2_fu_241_ap_start_reg;

assign icmp_ln18_fu_299_p2 = ((n_fu_128 < 4'd10) ? 1'b1 : 1'b0);

assign or_ln32_fu_441_p2 = (shl_ln1_fu_369_p3 | 6'd4);

assign sext_ln24_1_fu_512_p1 = $signed(trunc_ln24_1_reg_609);

assign sext_ln24_2_fu_530_p1 = $signed(trunc_ln24_2_reg_627);

assign sext_ln24_3_fu_335_p1 = sub_ln24_fu_329_p2;

assign sext_ln24_fu_281_p1 = trunc_ln_fu_271_p4;

assign sext_ln32_1_fu_421_p1 = $signed(trunc_ln32_1_fu_411_p4);

assign sext_ln32_2_fu_466_p1 = $signed(trunc_ln32_2_fu_456_p4);

assign sext_ln32_3_fu_491_p1 = $signed(trunc_ln32_3_fu_481_p4);

assign sext_ln32_fu_396_p1 = $signed(trunc_ln1_fu_386_p4);

assign shl_ln1_fu_369_p3 = {{n_fu_128}, {2'd0}};

assign shl_ln24_1_fu_317_p3 = {{n_fu_128}, {5'd0}};

assign shl_ln_fu_305_p3 = {{n_fu_128}, {9'd0}};

assign sub_ln24_fu_329_p2 = (zext_ln24_fu_313_p1 - zext_ln24_1_fu_325_p1);

assign trunc_ln1_fu_386_p4 = {{add_ln32_fu_381_p2[63:2]}};

assign trunc_ln32_1_fu_411_p4 = {{add_ln32_1_fu_406_p2[63:2]}};

assign trunc_ln32_2_fu_456_p4 = {{add_ln32_2_fu_451_p2[63:2]}};

assign trunc_ln32_3_fu_481_p4 = {{add_ln32_3_fu_476_p2[63:2]}};

assign trunc_ln_fu_271_p4 = {{input_r_r[63:2]}};

assign zext_ln24_1_fu_325_p1 = shl_ln24_1_fu_317_p3;

assign zext_ln24_2_fu_360_p1 = add_ln24_1_fu_354_p2;

assign zext_ln24_fu_313_p1 = shl_ln_fu_305_p3;

assign zext_ln32_1_fu_447_p1 = or_ln32_fu_441_p2;

assign zext_ln32_fu_377_p1 = shl_ln1_fu_369_p3;

endmodule //fc6_hls
