set SynModuleInfo {
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_4 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_4 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_4
    SUBMODULES {
      {MODELNAME convolution5_hls_flow_control_loop_pipe_sequential_init RTLNAME convolution5_hls_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME convolution5_hls_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_41 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_41 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_41}
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_42 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_42 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_42}
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_43 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_43 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_43}
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_44 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_44 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_44}
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_45 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_45 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_45}
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_46 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_46 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_46}
  {SRCNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_47 MODELNAME convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_47 RTLNAME convolution5_hls_convolution5_hls_Pipeline_VITIS_LOOP_24_2_VITIS_LOOP_25_3_VITIS_LOOP_26_47}
  {SRCNAME convolution5_hls MODELNAME convolution5_hls RTLNAME convolution5_hls IS_TOP 1
    SUBMODULES {
      {MODELNAME convolution5_hls_mul_7ns_12ns_18_1_1 RTLNAME convolution5_hls_mul_7ns_12ns_18_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME convolution5_hls_fmul_32ns_32ns_32_3_max_dsp_1 RTLNAME convolution5_hls_fmul_32ns_32ns_32_3_max_dsp_1 BINDTYPE op TYPE fmul IMPL maxdsp LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME convolution5_hls_fadd_32ns_32ns_32_4_full_dsp_1 RTLNAME convolution5_hls_fadd_32ns_32ns_32_4_full_dsp_1 BINDTYPE op TYPE fadd IMPL fulldsp LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME convolution5_hls_INPUT_r_m_axi RTLNAME convolution5_hls_INPUT_r_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME convolution5_hls_WEIGHTS_m_axi RTLNAME convolution5_hls_WEIGHTS_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME convolution5_hls_BIAS_m_axi RTLNAME convolution5_hls_BIAS_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME convolution5_hls_OUTPUT_r_m_axi RTLNAME convolution5_hls_OUTPUT_r_m_axi BINDTYPE interface TYPE adapter IMPL m_axi}
      {MODELNAME convolution5_hls_CTRL_BUS_s_axi RTLNAME convolution5_hls_CTRL_BUS_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME convolution5_hls_control_s_axi RTLNAME convolution5_hls_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
    }
  }
}
