-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity convolution3_hls_convolution3_hls_Pipeline_VITIS_LOOP_34_4_VITIS_LOOP_35_5_VITIS_LOOP_36_6_VITIS_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_WEIGHTS_AWVALID : OUT STD_LOGIC;
    m_axi_WEIGHTS_AWREADY : IN STD_LOGIC;
    m_axi_WEIGHTS_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WEIGHTS_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WEIGHTS_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_WVALID : OUT STD_LOGIC;
    m_axi_WEIGHTS_WREADY : IN STD_LOGIC;
    m_axi_WEIGHTS_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WEIGHTS_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_WLAST : OUT STD_LOGIC;
    m_axi_WEIGHTS_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_ARVALID : OUT STD_LOGIC;
    m_axi_WEIGHTS_ARREADY : IN STD_LOGIC;
    m_axi_WEIGHTS_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_WEIGHTS_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WEIGHTS_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_WEIGHTS_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_WEIGHTS_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_RVALID : IN STD_LOGIC;
    m_axi_WEIGHTS_RREADY : OUT STD_LOGIC;
    m_axi_WEIGHTS_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_WEIGHTS_RLAST : IN STD_LOGIC;
    m_axi_WEIGHTS_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_WEIGHTS_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_BVALID : IN STD_LOGIC;
    m_axi_WEIGHTS_BREADY : OUT STD_LOGIC;
    m_axi_WEIGHTS_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_WEIGHTS_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_WEIGHTS_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln34 : IN STD_LOGIC_VECTOR (61 downto 0);
    local_weights_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_ce0 : OUT STD_LOGIC;
    local_weights_we0 : OUT STD_LOGIC;
    local_weights_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_1_ce0 : OUT STD_LOGIC;
    local_weights_1_we0 : OUT STD_LOGIC;
    local_weights_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_2_ce0 : OUT STD_LOGIC;
    local_weights_2_we0 : OUT STD_LOGIC;
    local_weights_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_3_ce0 : OUT STD_LOGIC;
    local_weights_3_we0 : OUT STD_LOGIC;
    local_weights_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_4_ce0 : OUT STD_LOGIC;
    local_weights_4_we0 : OUT STD_LOGIC;
    local_weights_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_5_ce0 : OUT STD_LOGIC;
    local_weights_5_we0 : OUT STD_LOGIC;
    local_weights_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_6_ce0 : OUT STD_LOGIC;
    local_weights_6_we0 : OUT STD_LOGIC;
    local_weights_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_7_ce0 : OUT STD_LOGIC;
    local_weights_7_we0 : OUT STD_LOGIC;
    local_weights_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_8_ce0 : OUT STD_LOGIC;
    local_weights_8_we0 : OUT STD_LOGIC;
    local_weights_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_9_ce0 : OUT STD_LOGIC;
    local_weights_9_we0 : OUT STD_LOGIC;
    local_weights_9_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_10_ce0 : OUT STD_LOGIC;
    local_weights_10_we0 : OUT STD_LOGIC;
    local_weights_10_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_11_ce0 : OUT STD_LOGIC;
    local_weights_11_we0 : OUT STD_LOGIC;
    local_weights_11_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_12_ce0 : OUT STD_LOGIC;
    local_weights_12_we0 : OUT STD_LOGIC;
    local_weights_12_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_13_ce0 : OUT STD_LOGIC;
    local_weights_13_we0 : OUT STD_LOGIC;
    local_weights_13_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_14_ce0 : OUT STD_LOGIC;
    local_weights_14_we0 : OUT STD_LOGIC;
    local_weights_14_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    local_weights_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    local_weights_15_ce0 : OUT STD_LOGIC;
    local_weights_15_we0 : OUT STD_LOGIC;
    local_weights_15_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of convolution3_hls_convolution3_hls_Pipeline_VITIS_LOOP_34_4_VITIS_LOOP_35_5_VITIS_LOOP_36_6_VITIS_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv12_960 : STD_LOGIC_VECTOR (11 downto 0) := "100101100000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_96 : STD_LOGIC_VECTOR (7 downto 0) := "10010110";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv6_19 : STD_LOGIC_VECTOR (5 downto 0) := "011001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln34_reg_813 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln34_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal WEIGHTS_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln35_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln35_reg_817 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln34_fu_478_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln34_reg_826 : STD_LOGIC_VECTOR (3 downto 0);
    signal bitcast_ln39_fu_482_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bitcast_ln39_reg_830 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln39_5_fu_695_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal kw_fu_140 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln37_fu_718_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal kh_fu_144 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln36_1_fu_627_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten18_fu_148 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln36_2_fu_730_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ci_fu_152 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln35_1_fu_594_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten31_fu_156 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln35_2_fu_492_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal co_fu_160 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal select_ln34_1_fu_470_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten53_fu_164 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln34_1_fu_435_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten53_load : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln34_fu_458_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln35_1_fu_486_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln36_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln34_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln34_fu_522_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln34_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_fu_558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln35_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln35_1_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln34_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln37_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln35_fu_552_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln35_fu_563_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln35_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln36_fu_608_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln36_1_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln36_fu_602_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_10_fu_639_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln39_1_fu_647_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln39_fu_635_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln39_fu_651_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln39_2_fu_657_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln39_1_fu_661_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_671_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln39_3_fu_667_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln36_fu_619_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln39_2_fu_679_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln39_4_fu_685_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln39_3_fu_689_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln36_1_fu_724_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component convolution3_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component convolution3_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ci_fu_152_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ci_fu_152 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    ci_fu_152 <= select_ln35_1_fu_594_p3;
                end if;
            end if; 
        end if;
    end process;

    co_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    co_fu_160 <= ap_const_lv5_0;
                elsif (((icmp_ln34_reg_813 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    co_fu_160 <= select_ln34_1_fu_470_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten18_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    indvar_flatten18_fu_148 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    indvar_flatten18_fu_148 <= select_ln36_2_fu_730_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten31_fu_156_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten31_fu_156 <= ap_const_lv8_0;
                elsif (((icmp_ln34_reg_813 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten31_fu_156 <= select_ln35_2_fu_492_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten53_fu_164_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln34_fu_429_p2 = ap_const_lv1_0))) then 
                    indvar_flatten53_fu_164 <= add_ln34_1_fu_435_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten53_fu_164 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    kh_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    kh_fu_144 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    kh_fu_144 <= select_ln36_1_fu_627_p3;
                end if;
            end if; 
        end if;
    end process;

    kw_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    kw_fu_140 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    kw_fu_140 <= add_ln37_fu_718_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                bitcast_ln39_reg_830 <= bitcast_ln39_fu_482_p1;
                icmp_ln34_reg_813 <= icmp_ln34_fu_429_p2;
                icmp_ln35_reg_817 <= icmp_ln35_fu_464_p2;
                trunc_ln34_reg_826 <= trunc_ln34_fu_478_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    WEIGHTS_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_WEIGHTS_RVALID, icmp_ln34_reg_813, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln34_reg_813 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            WEIGHTS_blk_n_R <= m_axi_WEIGHTS_RVALID;
        else 
            WEIGHTS_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    add_ln34_1_fu_435_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten53_load) + unsigned(ap_const_lv12_1));
    add_ln34_fu_458_p2 <= std_logic_vector(unsigned(co_fu_160) + unsigned(ap_const_lv5_1));
    add_ln35_1_fu_486_p2 <= std_logic_vector(unsigned(indvar_flatten31_fu_156) + unsigned(ap_const_lv8_1));
    add_ln35_fu_552_p2 <= std_logic_vector(unsigned(select_ln34_fu_522_p3) + unsigned(ap_const_lv3_1));
    add_ln36_1_fu_724_p2 <= std_logic_vector(unsigned(indvar_flatten18_fu_148) + unsigned(ap_const_lv6_1));
    add_ln36_fu_602_p2 <= std_logic_vector(unsigned(select_ln35_fu_563_p3) + unsigned(ap_const_lv3_1));
    add_ln37_fu_718_p2 <= std_logic_vector(unsigned(select_ln36_fu_619_p3) + unsigned(ap_const_lv3_1));
    add_ln39_1_fu_661_p2 <= std_logic_vector(unsigned(add_ln39_fu_651_p2) + unsigned(zext_ln39_2_fu_657_p1));
    add_ln39_2_fu_679_p2 <= std_logic_vector(unsigned(tmp_fu_671_p3) + unsigned(zext_ln39_3_fu_667_p1));
    add_ln39_3_fu_689_p2 <= std_logic_vector(unsigned(add_ln39_2_fu_679_p2) + unsigned(zext_ln39_4_fu_685_p1));
    add_ln39_fu_651_p2 <= std_logic_vector(unsigned(zext_ln39_1_fu_647_p1) + unsigned(zext_ln39_fu_635_p1));
    and_ln34_1_fu_546_p2 <= (xor_ln34_fu_529_p2 and icmp_ln36_fu_540_p2);
    and_ln34_fu_582_p2 <= (xor_ln34_fu_529_p2 and or_ln35_1_fu_577_p2);
    and_ln35_fu_588_p2 <= (icmp_ln37_fu_534_p2 and and_ln34_fu_582_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(m_axi_WEIGHTS_RVALID, icmp_ln34_reg_813)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln34_reg_813 = ap_const_lv1_0) and (m_axi_WEIGHTS_RVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln34_fu_429_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln34_fu_429_p2 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln34_reg_813, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln34_reg_813 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten53_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten53_fu_164)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten53_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten53_load <= indvar_flatten53_fu_164;
        end if; 
    end process;

    bitcast_ln39_fu_482_p1 <= m_axi_WEIGHTS_RDATA;
    icmp_ln34_fu_429_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten53_load = ap_const_lv12_960) else "0";
    icmp_ln35_fu_464_p2 <= "1" when (indvar_flatten31_fu_156 = ap_const_lv8_96) else "0";
    icmp_ln36_fu_540_p2 <= "1" when (indvar_flatten18_fu_148 = ap_const_lv6_19) else "0";
    icmp_ln37_fu_534_p2 <= "1" when (kw_fu_140 = ap_const_lv3_5) else "0";
    local_weights_10_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_10_ce0 <= ap_const_logic_1;
        else 
            local_weights_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_10_d0 <= bitcast_ln39_reg_830;

    local_weights_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_A))) then 
            local_weights_10_we0 <= ap_const_logic_1;
        else 
            local_weights_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_11_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_11_ce0 <= ap_const_logic_1;
        else 
            local_weights_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_11_d0 <= bitcast_ln39_reg_830;

    local_weights_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_B))) then 
            local_weights_11_we0 <= ap_const_logic_1;
        else 
            local_weights_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_12_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_12_ce0 <= ap_const_logic_1;
        else 
            local_weights_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_12_d0 <= bitcast_ln39_reg_830;

    local_weights_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_C))) then 
            local_weights_12_we0 <= ap_const_logic_1;
        else 
            local_weights_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_13_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_13_ce0 <= ap_const_logic_1;
        else 
            local_weights_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_13_d0 <= bitcast_ln39_reg_830;

    local_weights_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_D))) then 
            local_weights_13_we0 <= ap_const_logic_1;
        else 
            local_weights_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_14_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_14_ce0 <= ap_const_logic_1;
        else 
            local_weights_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_14_d0 <= bitcast_ln39_reg_830;

    local_weights_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_E))) then 
            local_weights_14_we0 <= ap_const_logic_1;
        else 
            local_weights_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_15_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_15_ce0 <= ap_const_logic_1;
        else 
            local_weights_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_15_d0 <= bitcast_ln39_reg_830;

    local_weights_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_F))) then 
            local_weights_15_we0 <= ap_const_logic_1;
        else 
            local_weights_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_1_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_1_ce0 <= ap_const_logic_1;
        else 
            local_weights_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_1_d0 <= bitcast_ln39_reg_830;

    local_weights_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_1))) then 
            local_weights_1_we0 <= ap_const_logic_1;
        else 
            local_weights_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_2_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_2_ce0 <= ap_const_logic_1;
        else 
            local_weights_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_2_d0 <= bitcast_ln39_reg_830;

    local_weights_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_2))) then 
            local_weights_2_we0 <= ap_const_logic_1;
        else 
            local_weights_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_3_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_3_ce0 <= ap_const_logic_1;
        else 
            local_weights_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_3_d0 <= bitcast_ln39_reg_830;

    local_weights_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_3))) then 
            local_weights_3_we0 <= ap_const_logic_1;
        else 
            local_weights_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_4_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_4_ce0 <= ap_const_logic_1;
        else 
            local_weights_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_4_d0 <= bitcast_ln39_reg_830;

    local_weights_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_4))) then 
            local_weights_4_we0 <= ap_const_logic_1;
        else 
            local_weights_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_5_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_5_ce0 <= ap_const_logic_1;
        else 
            local_weights_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_5_d0 <= bitcast_ln39_reg_830;

    local_weights_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_5))) then 
            local_weights_5_we0 <= ap_const_logic_1;
        else 
            local_weights_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_6_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_6_ce0 <= ap_const_logic_1;
        else 
            local_weights_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_6_d0 <= bitcast_ln39_reg_830;

    local_weights_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_6))) then 
            local_weights_6_we0 <= ap_const_logic_1;
        else 
            local_weights_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_7_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_7_ce0 <= ap_const_logic_1;
        else 
            local_weights_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_7_d0 <= bitcast_ln39_reg_830;

    local_weights_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_7))) then 
            local_weights_7_we0 <= ap_const_logic_1;
        else 
            local_weights_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_8_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_8_ce0 <= ap_const_logic_1;
        else 
            local_weights_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_8_d0 <= bitcast_ln39_reg_830;

    local_weights_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_8))) then 
            local_weights_8_we0 <= ap_const_logic_1;
        else 
            local_weights_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_9_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_9_ce0 <= ap_const_logic_1;
        else 
            local_weights_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_9_d0 <= bitcast_ln39_reg_830;

    local_weights_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_9))) then 
            local_weights_9_we0 <= ap_const_logic_1;
        else 
            local_weights_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_address0 <= zext_ln39_5_fu_695_p1(8 - 1 downto 0);

    local_weights_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            local_weights_ce0 <= ap_const_logic_1;
        else 
            local_weights_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    local_weights_d0 <= bitcast_ln39_reg_830;

    local_weights_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, trunc_ln34_reg_826)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (trunc_ln34_reg_826 = ap_const_lv4_0))) then 
            local_weights_we0 <= ap_const_logic_1;
        else 
            local_weights_we0 <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_WEIGHTS_ARADDR <= ap_const_lv64_0;
    m_axi_WEIGHTS_ARBURST <= ap_const_lv2_0;
    m_axi_WEIGHTS_ARCACHE <= ap_const_lv4_0;
    m_axi_WEIGHTS_ARID <= ap_const_lv1_0;
    m_axi_WEIGHTS_ARLEN <= ap_const_lv32_0;
    m_axi_WEIGHTS_ARLOCK <= ap_const_lv2_0;
    m_axi_WEIGHTS_ARPROT <= ap_const_lv3_0;
    m_axi_WEIGHTS_ARQOS <= ap_const_lv4_0;
    m_axi_WEIGHTS_ARREGION <= ap_const_lv4_0;
    m_axi_WEIGHTS_ARSIZE <= ap_const_lv3_0;
    m_axi_WEIGHTS_ARUSER <= ap_const_lv1_0;
    m_axi_WEIGHTS_ARVALID <= ap_const_logic_0;
    m_axi_WEIGHTS_AWADDR <= ap_const_lv64_0;
    m_axi_WEIGHTS_AWBURST <= ap_const_lv2_0;
    m_axi_WEIGHTS_AWCACHE <= ap_const_lv4_0;
    m_axi_WEIGHTS_AWID <= ap_const_lv1_0;
    m_axi_WEIGHTS_AWLEN <= ap_const_lv32_0;
    m_axi_WEIGHTS_AWLOCK <= ap_const_lv2_0;
    m_axi_WEIGHTS_AWPROT <= ap_const_lv3_0;
    m_axi_WEIGHTS_AWQOS <= ap_const_lv4_0;
    m_axi_WEIGHTS_AWREGION <= ap_const_lv4_0;
    m_axi_WEIGHTS_AWSIZE <= ap_const_lv3_0;
    m_axi_WEIGHTS_AWUSER <= ap_const_lv1_0;
    m_axi_WEIGHTS_AWVALID <= ap_const_logic_0;
    m_axi_WEIGHTS_BREADY <= ap_const_logic_0;

    m_axi_WEIGHTS_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln34_reg_813, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln34_reg_813 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axi_WEIGHTS_RREADY <= ap_const_logic_1;
        else 
            m_axi_WEIGHTS_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_WEIGHTS_WDATA <= ap_const_lv32_0;
    m_axi_WEIGHTS_WID <= ap_const_lv1_0;
    m_axi_WEIGHTS_WLAST <= ap_const_logic_0;
    m_axi_WEIGHTS_WSTRB <= ap_const_lv4_0;
    m_axi_WEIGHTS_WUSER <= ap_const_lv1_0;
    m_axi_WEIGHTS_WVALID <= ap_const_logic_0;
    or_ln35_1_fu_577_p2 <= (xor_ln35_fu_571_p2 or icmp_ln35_reg_817);
    or_ln35_fu_558_p2 <= (icmp_ln35_reg_817 or and_ln34_1_fu_546_p2);
    or_ln36_1_fu_614_p2 <= (or_ln36_fu_608_p2 or icmp_ln35_reg_817);
    or_ln36_fu_608_p2 <= (and_ln35_fu_588_p2 or and_ln34_1_fu_546_p2);
    select_ln34_1_fu_470_p3 <= 
        add_ln34_fu_458_p2 when (icmp_ln35_fu_464_p2(0) = '1') else 
        co_fu_160;
    select_ln34_fu_522_p3 <= 
        ap_const_lv3_0 when (icmp_ln35_reg_817(0) = '1') else 
        ci_fu_152;
    select_ln35_1_fu_594_p3 <= 
        add_ln35_fu_552_p2 when (and_ln34_1_fu_546_p2(0) = '1') else 
        select_ln34_fu_522_p3;
    select_ln35_2_fu_492_p3 <= 
        ap_const_lv8_1 when (icmp_ln35_fu_464_p2(0) = '1') else 
        add_ln35_1_fu_486_p2;
    select_ln35_fu_563_p3 <= 
        ap_const_lv3_0 when (or_ln35_fu_558_p2(0) = '1') else 
        kh_fu_144;
    select_ln36_1_fu_627_p3 <= 
        add_ln36_fu_602_p2 when (and_ln35_fu_588_p2(0) = '1') else 
        select_ln35_fu_563_p3;
    select_ln36_2_fu_730_p3 <= 
        ap_const_lv6_1 when (or_ln35_fu_558_p2(0) = '1') else 
        add_ln36_1_fu_724_p2;
    select_ln36_fu_619_p3 <= 
        ap_const_lv3_0 when (or_ln36_1_fu_614_p2(0) = '1') else 
        kw_fu_140;
    tmp_10_fu_639_p3 <= (select_ln35_1_fu_594_p3 & ap_const_lv2_0);
    tmp_fu_671_p3 <= (add_ln39_1_fu_661_p2 & ap_const_lv2_0);
    trunc_ln34_fu_478_p1 <= select_ln34_1_fu_470_p3(4 - 1 downto 0);
    xor_ln34_fu_529_p2 <= (icmp_ln35_reg_817 xor ap_const_lv1_1);
    xor_ln35_fu_571_p2 <= (icmp_ln36_fu_540_p2 xor ap_const_lv1_1);
    zext_ln39_1_fu_647_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_639_p3),6));
    zext_ln39_2_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln36_1_fu_627_p3),6));
    zext_ln39_3_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln39_1_fu_661_p2),8));
    zext_ln39_4_fu_685_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln36_fu_619_p3),8));
    zext_ln39_5_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln39_3_fu_689_p2),64));
    zext_ln39_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln35_1_fu_594_p3),6));
end behav;
