# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_3/design_1_axi_smc_3.xci
# IP: The module: 'design_1_axi_smc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/bd_ae83.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_0/bd_ae83_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_1/bd_ae83_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_2/bd_ae83_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_3/bd_ae83_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_4/bd_ae83_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_5/bd_ae83_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_6/bd_ae83_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_7/bd_ae83_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_8/bd_ae83_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_9/bd_ae83_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_1/bd_ae83_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_1/bd_ae83_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_5/bd_ae83_s00a2s_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_6/bd_ae83_sarn_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_6/bd_ae83_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_7/bd_ae83_srn_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_7/bd_ae83_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_8/bd_ae83_m00s2a_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_3/design_1_axi_smc_3.xci
# IP: The module: 'design_1_axi_smc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/bd_ae83.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_0/bd_ae83_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_1/bd_ae83_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_2/bd_ae83_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_3/bd_ae83_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_4/bd_ae83_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_5/bd_ae83_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_6/bd_ae83_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_7/bd_ae83_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_8/bd_ae83_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_9/bd_ae83_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_1/bd_ae83_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_1/bd_ae83_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_5/bd_ae83_s00a2s_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_6/bd_ae83_sarn_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_6/bd_ae83_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_7/bd_ae83_srn_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_7/bd_ae83_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/bd_0/ip/ip_8/bd_ae83_m00s2a_0_ooc.xdc

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_optimized_final/matmul_optimized_final.gen/sources_1/bd/design_1/ip/design_1_axi_smc_3/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_smc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
