# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_no_op_final_vivado/matmul_no_op_final_vivado.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_no_op_final_vivado/matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_no_op_final_vivado/matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_no_op_final_vivado/matmul_no_op_final_vivado.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
# IP: The module: 'design_1_zynq_ultra_ps_e_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_no_op_final_vivado/matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Xilinx_Prj/SoC-based-MatMul-Accelerator-and-DNN-Accelerator/eecs298soc/matmul_no_op_final_vivado/matmul_no_op_final_vivado.gen/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_zynq_ultra_ps_e_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
